//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace org.DownesWard.Traveller.SystemGeneration.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Languages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Languages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("org.DownesWard.Traveller.SystemGeneration.Resources.Languages", typeof(Languages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M.
        /// </summary>
        internal static string Base_Military {
            get {
                return ResourceManager.GetString("Base_Military", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        internal static string Base_Naval {
            get {
                return ResourceManager.GetString("Base_Naval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        internal static string Base_Scout {
            get {
                return ResourceManager.GetString("Base_Scout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Colony.
        /// </summary>
        internal static string ColonyAge_Middle {
            get {
                return ResourceManager.GetString("ColonyAge_Middle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Colony.
        /// </summary>
        internal static string ColonyAge_Old {
            get {
                return ResourceManager.GetString("ColonyAge_Old", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Young Colony.
        /// </summary>
        internal static string ColonyAge_Young {
            get {
                return ResourceManager.GetString("ColonyAge_Young", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companion Star.
        /// </summary>
        internal static string CompanionStar {
            get {
                return ResourceManager.GetString("CompanionStar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civil War.
        /// </summary>
        internal static string Conflict_CivilWar {
            get {
                return ResourceManager.GetString("Conflict_CivilWar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethnic or Religious Divide.
        /// </summary>
        internal static string Conflict_Divide {
            get {
                return ResourceManager.GetString("Conflict_Divide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Coup.
        /// </summary>
        internal static string Conflict_FailedCoup {
            get {
                return ResourceManager.GetString("Conflict_FailedCoup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invasion ({0}).
        /// </summary>
        internal static string Conflict_Invasion {
            get {
                return ResourceManager.GetString("Conflict_Invasion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peacekeeping.
        /// </summary>
        internal static string Conflict_Peacekeeping {
            get {
                return ResourceManager.GetString("Conflict_Peacekeeping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebellion against off-world interests.
        /// </summary>
        internal static string Conflict_RebellionOffWorld {
            get {
                return ResourceManager.GetString("Conflict_RebellionOffWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebellion against parent world.
        /// </summary>
        internal static string Conflict_RebellionParent {
            get {
                return ResourceManager.GetString("Conflict_RebellionParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource War.
        /// </summary>
        internal static string Conflict_ResourceWar {
            get {
                return ResourceManager.GetString("Conflict_ResourceWar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Territory War.
        /// </summary>
        internal static string Conflict_Territory {
            get {
                return ResourceManager.GetString("Conflict_Territory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade War.
        /// </summary>
        internal static string Conflict_TradeWar {
            get {
                return ResourceManager.GetString("Conflict_TradeWar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Government: {0}, Strength: {1}.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South American (Amazon Basin).
        /// </summary>
        internal static string FactionOrigin_AmazonBasin {
            get {
                return ResourceManager.GetString("FactionOrigin_AmazonBasin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South American (Andean).
        /// </summary>
        internal static string FactionOrigin_Andean {
            get {
                return ResourceManager.GetString("FactionOrigin_Andean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to European - British Isles.
        /// </summary>
        internal static string FactionOrigin_BritishIsles {
            get {
                return ResourceManager.GetString("FactionOrigin_BritishIsles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canadian.
        /// </summary>
        internal static string FactionOrigin_Canadian {
            get {
                return ResourceManager.GetString("FactionOrigin_Canadian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catholic.
        /// </summary>
        internal static string FactionOrigin_Catholic {
            get {
                return ResourceManager.GetString("FactionOrigin_Catholic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central American.
        /// </summary>
        internal static string FactionOrigin_CentralAmerican {
            get {
                return ResourceManager.GetString("FactionOrigin_CentralAmerican", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eastern United States.
        /// </summary>
        internal static string FactionOrigin_EastUS {
            get {
                return ResourceManager.GetString("FactionOrigin_EastUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evangelical Christian.
        /// </summary>
        internal static string FactionOrigin_Evangelical {
            get {
                return ResourceManager.GetString("FactionOrigin_Evangelical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mexican.
        /// </summary>
        internal static string FactionOrigin_Mexican {
            get {
                return ResourceManager.GetString("FactionOrigin_Mexican", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Midwest United States.
        /// </summary>
        internal static string FactionOrigin_MidWestUS {
            get {
                return ResourceManager.GetString("FactionOrigin_MidWestUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to European - Scandanavian.
        /// </summary>
        internal static string FactionOrigin_Scandinavian {
            get {
                return ResourceManager.GetString("FactionOrigin_Scandinavian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South American (South).
        /// </summary>
        internal static string FactionOrigin_SouthAmerican {
            get {
                return ResourceManager.GetString("FactionOrigin_SouthAmerican", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Southern United States.
        /// </summary>
        internal static string FactionOrigin_SouthUS {
            get {
                return ResourceManager.GetString("FactionOrigin_SouthUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Western United States.
        /// </summary>
        internal static string FactionOrigin_WestUS {
            get {
                return ResourceManager.GetString("FactionOrigin_WestUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string Gov_0 {
            get {
                return ResourceManager.GetString("Gov_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string Gov_1 {
            get {
                return ResourceManager.GetString("Gov_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charismatic Dictator.
        /// </summary>
        internal static string Gov_10 {
            get {
                return ResourceManager.GetString("Gov_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-charismatic Dictator.
        /// </summary>
        internal static string Gov_11 {
            get {
                return ResourceManager.GetString("Gov_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charismatic oligarchy.
        /// </summary>
        internal static string Gov_12 {
            get {
                return ResourceManager.GetString("Gov_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Religious Dictatorship.
        /// </summary>
        internal static string Gov_13 {
            get {
                return ResourceManager.GetString("Gov_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participating Democracy.
        /// </summary>
        internal static string Gov_2 {
            get {
                return ResourceManager.GetString("Gov_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self perpetuating oligarchy.
        /// </summary>
        internal static string Gov_3 {
            get {
                return ResourceManager.GetString("Gov_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Representative Democracy.
        /// </summary>
        internal static string Gov_4 {
            get {
                return ResourceManager.GetString("Gov_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feudal Technocracy.
        /// </summary>
        internal static string Gov_5 {
            get {
                return ResourceManager.GetString("Gov_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off world interests.
        /// </summary>
        internal static string Gov_6 {
            get {
                return ResourceManager.GetString("Gov_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anarchists.
        /// </summary>
        internal static string Gov_7 {
            get {
                return ResourceManager.GetString("Gov_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civil Service Bureaucracy.
        /// </summary>
        internal static string Gov_8 {
            get {
                return ResourceManager.GetString("Gov_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impersonal Bureaucracy.
        /// </summary>
        internal static string Gov_9 {
            get {
                return ResourceManager.GetString("Gov_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other ({0}).
        /// </summary>
        internal static string Gov_Other {
            get {
                return ResourceManager.GetString("Gov_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: {0},.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin: {0},.
        /// </summary>
        internal static string Origin {
            get {
                return ResourceManager.GetString("Origin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obscure Group.
        /// </summary>
        internal static string Str_1 {
            get {
                return ResourceManager.GetString("Str_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fringe Group.
        /// </summary>
        internal static string Str_2 {
            get {
                return ResourceManager.GetString("Str_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minor Group.
        /// </summary>
        internal static string Str_3 {
            get {
                return ResourceManager.GetString("Str_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notable Group.
        /// </summary>
        internal static string Str_4 {
            get {
                return ResourceManager.GetString("Str_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Significant Group.
        /// </summary>
        internal static string Str_5 {
            get {
                return ResourceManager.GetString("Str_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwelming Popular Support.
        /// </summary>
        internal static string Str_6 {
            get {
                return ResourceManager.GetString("Str_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nv.
        /// </summary>
        internal static string Subbase_Naval {
            get {
                return ResourceManager.GetString("Subbase_Naval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sc.
        /// </summary>
        internal static string Subbase_Scout {
            get {
                return ResourceManager.GetString("Subbase_Scout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ag.
        /// </summary>
        internal static string TradeCode_Agricultural {
            get {
                return ResourceManager.GetString("TradeCode_Agricultural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As.
        /// </summary>
        internal static string TradeCode_Asteroid {
            get {
                return ResourceManager.GetString("TradeCode_Asteroid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ba.
        /// </summary>
        internal static string TradeCode_Barren {
            get {
                return ResourceManager.GetString("TradeCode_Barren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Co.
        /// </summary>
        internal static string TradeCode_Colony {
            get {
                return ResourceManager.GetString("TradeCode_Colony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De.
        /// </summary>
        internal static string TradeCode_Desert {
            get {
                return ResourceManager.GetString("TradeCode_Desert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fa.
        /// </summary>
        internal static string TradeCode_FarmingColony {
            get {
                return ResourceManager.GetString("TradeCode_FarmingColony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fl.
        /// </summary>
        internal static string TradeCode_FluidOceans {
            get {
                return ResourceManager.GetString("TradeCode_FluidOceans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi.
        /// </summary>
        internal static string TradeCode_HighPopulation {
            get {
                return ResourceManager.GetString("TradeCode_HighPopulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ic.
        /// </summary>
        internal static string TradeCode_IceCapped {
            get {
                return ResourceManager.GetString("TradeCode_IceCapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In.
        /// </summary>
        internal static string TradeCode_Industrial {
            get {
                return ResourceManager.GetString("TradeCode_Industrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lo.
        /// </summary>
        internal static string TradeCode_LowPopulation {
            get {
                return ResourceManager.GetString("TradeCode_LowPopulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mn.
        /// </summary>
        internal static string TradeCode_MiningColony {
            get {
                return ResourceManager.GetString("TradeCode_MiningColony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Na.
        /// </summary>
        internal static string TradeCode_NonAgricultural {
            get {
                return ResourceManager.GetString("TradeCode_NonAgricultural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ni.
        /// </summary>
        internal static string TradeCode_NonIndustrial {
            get {
                return ResourceManager.GetString("TradeCode_NonIndustrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Po.
        /// </summary>
        internal static string TradeCode_Poor {
            get {
                return ResourceManager.GetString("TradeCode_Poor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re.
        /// </summary>
        internal static string TradeCode_ResearchColony {
            get {
                return ResourceManager.GetString("TradeCode_ResearchColony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ri.
        /// </summary>
        internal static string TradeCode_Rich {
            get {
                return ResourceManager.GetString("TradeCode_Rich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Va.
        /// </summary>
        internal static string TradeCode_VaccumWorld {
            get {
                return ResourceManager.GetString("TradeCode_VaccumWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wa.
        /// </summary>
        internal static string TradeCode_WaterWorld {
            get {
                return ResourceManager.GetString("TradeCode_WaterWorld", resourceCulture);
            }
        }
    }
}
