//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace org.DownesWard.Traveller.CharacterGeneration.Classic.Aslan {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("org.DownesWard.Traveller.CharacterGeneration.Classic.Aslan.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belter.
        /// </summary>
        internal static string Career_Belter {
            get {
                return ResourceManager.GetString("Career_Belter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envoy.
        /// </summary>
        internal static string Career_Envoy {
            get {
                return ResourceManager.GetString("Career_Envoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flyer.
        /// </summary>
        internal static string Career_Flyer {
            get {
                return ResourceManager.GetString("Career_Flyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        internal static string Career_Management {
            get {
                return ResourceManager.GetString("Career_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medic.
        /// </summary>
        internal static string Career_Medic {
            get {
                return ResourceManager.GetString("Career_Medic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Military.
        /// </summary>
        internal static string Career_Military {
            get {
                return ResourceManager.GetString("Career_Military", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Military Officer.
        /// </summary>
        internal static string Career_MilitaryOfficer {
            get {
                return ResourceManager.GetString("Career_MilitaryOfficer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outcast.
        /// </summary>
        internal static string Career_Outcast {
            get {
                return ResourceManager.GetString("Career_Outcast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pirate.
        /// </summary>
        internal static string Career_Pirate {
            get {
                return ResourceManager.GetString("Career_Pirate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scientist.
        /// </summary>
        internal static string Career_Scientist {
            get {
                return ResourceManager.GetString("Career_Scientist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space.
        /// </summary>
        internal static string Career_Space {
            get {
                return ResourceManager.GetString("Career_Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space Officer.
        /// </summary>
        internal static string Career_SpaceOfficer {
            get {
                return ResourceManager.GetString("Career_SpaceOfficer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wanderer.
        /// </summary>
        internal static string Career_Wanderer {
            get {
                return ResourceManager.GetString("Career_Wanderer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOC Raised to 9 due to being commissioned..
        /// </summary>
        internal static string Msg_Commision {
            get {
                return ResourceManager.GetString("Msg_Commision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rite of Passage Score is {0}..
        /// </summary>
        internal static string Msg_ROPScore {
            get {
                return ResourceManager.GetString("Msg_ROPScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adminstrator.
        /// </summary>
        internal static string Rank_Adminstrator {
            get {
                return ResourceManager.GetString("Rank_Adminstrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admiral.
        /// </summary>
        internal static string Rank_Admiral {
            get {
                return ResourceManager.GetString("Rank_Admiral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air Marshal.
        /// </summary>
        internal static string Rank_AirMarshal {
            get {
                return ResourceManager.GetString("Rank_AirMarshal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belter.
        /// </summary>
        internal static string Rank_Belter {
            get {
                return ResourceManager.GetString("Rank_Belter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadet.
        /// </summary>
        internal static string Rank_Cadet {
            get {
                return ResourceManager.GetString("Rank_Cadet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain.
        /// </summary>
        internal static string Rank_Captain {
            get {
                return ResourceManager.GetString("Rank_Captain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chief of Staff.
        /// </summary>
        internal static string Rank_ChiefOfStaff {
            get {
                return ResourceManager.GetString("Rank_ChiefOfStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clerk.
        /// </summary>
        internal static string Rank_Clerk {
            get {
                return ResourceManager.GetString("Rank_Clerk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commandant.
        /// </summary>
        internal static string Rank_Commandant {
            get {
                return ResourceManager.GetString("Rank_Commandant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commandant Lieutenant.
        /// </summary>
        internal static string Rank_CommandantLieutenant {
            get {
                return ResourceManager.GetString("Rank_CommandantLieutenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Director.
        /// </summary>
        internal static string Rank_Director {
            get {
                return ResourceManager.GetString("Rank_Director", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor.
        /// </summary>
        internal static string Rank_Doctor {
            get {
                return ResourceManager.GetString("Rank_Doctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envoy.
        /// </summary>
        internal static string Rank_Envoy {
            get {
                return ResourceManager.GetString("Rank_Envoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executive.
        /// </summary>
        internal static string Rank_Executive {
            get {
                return ResourceManager.GetString("Rank_Executive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executive Lieutenant.
        /// </summary>
        internal static string Rank_ExecutiveLieutenant {
            get {
                return ResourceManager.GetString("Rank_ExecutiveLieutenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight Commandant.
        /// </summary>
        internal static string Rank_FlightCommandant {
            get {
                return ResourceManager.GetString("Rank_FlightCommandant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flyer.
        /// </summary>
        internal static string Rank_Flyer {
            get {
                return ResourceManager.GetString("Rank_Flyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string Rank_General {
            get {
                return ResourceManager.GetString("Rank_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Leader.
        /// </summary>
        internal static string Rank_GroupLeader {
            get {
                return ResourceManager.GetString("Rank_GroupLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intendant.
        /// </summary>
        internal static string Rank_Intendant {
            get {
                return ResourceManager.GetString("Rank_Intendant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lieutenant.
        /// </summary>
        internal static string Rank_Lieutenant {
            get {
                return ResourceManager.GetString("Rank_Lieutenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        internal static string Rank_Manager {
            get {
                return ResourceManager.GetString("Rank_Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medic.
        /// </summary>
        internal static string Rank_Medic {
            get {
                return ResourceManager.GetString("Rank_Medic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Officer.
        /// </summary>
        internal static string Rank_Officer {
            get {
                return ResourceManager.GetString("Rank_Officer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outcast.
        /// </summary>
        internal static string Rank_Outcast {
            get {
                return ResourceManager.GetString("Rank_Outcast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pilot.
        /// </summary>
        internal static string Rank_Pilot {
            get {
                return ResourceManager.GetString("Rank_Pilot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pirate.
        /// </summary>
        internal static string Rank_Pirate {
            get {
                return ResourceManager.GetString("Rank_Pirate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scientist.
        /// </summary>
        internal static string Rank_Scientist {
            get {
                return ResourceManager.GetString("Rank_Scientist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senior Commandant.
        /// </summary>
        internal static string Rank_SeniorCommandant {
            get {
                return ResourceManager.GetString("Rank_SeniorCommandant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senior Executive.
        /// </summary>
        internal static string Rank_SeniorExecutive {
            get {
                return ResourceManager.GetString("Rank_SeniorExecutive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senior Lieutenant.
        /// </summary>
        internal static string Rank_SeniorLieutenant {
            get {
                return ResourceManager.GetString("Rank_SeniorLieutenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soldier.
        /// </summary>
        internal static string Rank_Soldier {
            get {
                return ResourceManager.GetString("Rank_Soldier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spacer.
        /// </summary>
        internal static string Rank_Spacer {
            get {
                return ResourceManager.GetString("Rank_Spacer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Squadron Leader.
        /// </summary>
        internal static string Rank_SquadronLeader {
            get {
                return ResourceManager.GetString("Rank_SquadronLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor.
        /// </summary>
        internal static string Rank_Supervisor {
            get {
                return ResourceManager.GetString("Rank_Supervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surgeon.
        /// </summary>
        internal static string Rank_Surgeon {
            get {
                return ResourceManager.GetString("Rank_Surgeon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trooper.
        /// </summary>
        internal static string Rank_Trooper {
            get {
                return ResourceManager.GetString("Rank_Trooper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veteran.
        /// </summary>
        internal static string Rank_Veteran {
            get {
                return ResourceManager.GetString("Rank_Veteran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wanderer.
        /// </summary>
        internal static string Rank_Wanderer {
            get {
                return ResourceManager.GetString("Rank_Wanderer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warrior.
        /// </summary>
        internal static string Rank_Warrior {
            get {
                return ResourceManager.GetString("Rank_Warrior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wing Leader.
        /// </summary>
        internal static string Rank_WingLeader {
            get {
                return ResourceManager.GetString("Rank_WingLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akhaeh.
        /// </summary>
        internal static string Skill_Akhaeh {
            get {
                return ResourceManager.GetString("Skill_Akhaeh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eakhyasear (Hunters Rifle).
        /// </summary>
        internal static string Skill_EakhyasearHuntersRifle {
            get {
                return ResourceManager.GetString("Skill_EakhyasearHuntersRifle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fierah.
        /// </summary>
        internal static string Skill_Fierah {
            get {
                return ResourceManager.GetString("Skill_Fierah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gun Combat.
        /// </summary>
        internal static string Skill_GunCombat {
            get {
                return ResourceManager.GetString("Skill_GunCombat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khaifealate (Machine Pistol).
        /// </summary>
        internal static string Skill_KhaifealateMachinePistol {
            get {
                return ResourceManager.GetString("Skill_KhaifealateMachinePistol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khaihte (Pistol).
        /// </summary>
        internal static string Skill_KhaihtePistol {
            get {
                return ResourceManager.GetString("Skill_KhaihtePistol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Weapons.
        /// </summary>
        internal static string Skill_PersonalWeapons {
            get {
                return ResourceManager.GetString("Skill_PersonalWeapons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spear.
        /// </summary>
        internal static string Skill_Spear {
            get {
                return ResourceManager.GetString("Skill_Spear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takheal (Long Rifle).
        /// </summary>
        internal static string Skill_TakhealLongRifle {
            get {
                return ResourceManager.GetString("Skill_TakhealLongRifle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takhestah (Long Pistol).
        /// </summary>
        internal static string Skill_TakhestahLongPistol {
            get {
                return ResourceManager.GetString("Skill_TakhestahLongPistol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triluealikhe (Laser Carbine).
        /// </summary>
        internal static string Skill_TriluealikheLaserCarbine {
            get {
                return ResourceManager.GetString("Skill_TriluealikheLaserCarbine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trolitakheal (Laser Rifle).
        /// </summary>
        internal static string Skill_TrolitakhealLaserRifle {
            get {
                return ResourceManager.GetString("Skill_TrolitakhealLaserRifle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uealikhe (Carbine).
        /// </summary>
        internal static string Skill_UealikheCarbine {
            get {
                return ResourceManager.GetString("Skill_UealikheCarbine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeheal (Automatic Rifle).
        /// </summary>
        internal static string Skill_YehealAutomaticRifle {
            get {
                return ResourceManager.GetString("Skill_YehealAutomaticRifle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yurletya.
        /// </summary>
        internal static string Skill_Yurletya {
            get {
                return ResourceManager.GetString("Skill_Yurletya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Service Skills.
        /// </summary>
        internal static string Table_AdvancedServiceSkills {
            get {
                return ResourceManager.GetString("Table_AdvancedServiceSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience.
        /// </summary>
        internal static string Table_Experience {
            get {
                return ResourceManager.GetString("Table_Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Development.
        /// </summary>
        internal static string Table_PersonalDevelopment {
            get {
                return ResourceManager.GetString("Table_PersonalDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Skills.
        /// </summary>
        internal static string Table_ServiceSkills {
            get {
                return ResourceManager.GetString("Table_ServiceSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Skills (Female).
        /// </summary>
        internal static string Table_ServiceSkillsFemale {
            get {
                return ResourceManager.GetString("Table_ServiceSkillsFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Skills (Male).
        /// </summary>
        internal static string Table_ServiceSkillsMale {
            get {
                return ResourceManager.GetString("Table_ServiceSkillsMale", resourceCulture);
            }
        }
    }
}
