//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace org.DownesWard.Traveller.CharacterGeneration.Cepheus.Hostile {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("org.DownesWard.Traveller.CharacterGeneration.Cepheus.Hostile.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elite Ticket.
        /// </summary>
        internal static string Benefit_EliteTicket {
            get {
                return ResourceManager.GetString("Benefit_EliteTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Ticket.
        /// </summary>
        internal static string Benefit_StandardTicket {
            get {
                return ResourceManager.GetString("Benefit_StandardTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star Envoy Club Member.
        /// </summary>
        internal static string Benefit_StarEnvoyClubMember {
            get {
                return ResourceManager.GetString("Benefit_StarEnvoyClubMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colonist.
        /// </summary>
        internal static string Career_Colonist {
            get {
                return ResourceManager.GetString("Career_Colonist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranger.
        /// </summary>
        internal static string Career_Ranger {
            get {
                return ResourceManager.GetString("Career_Ranger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roughneck.
        /// </summary>
        internal static string Career_Roughneck {
            get {
                return ResourceManager.GetString("Career_Roughneck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A colony accident left you injured..
        /// </summary>
        internal static string Mishap_ColonyAccident {
            get {
                return ResourceManager.GetString("Mishap_ColonyAccident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your colony is struck by disaster and you took some of the blame..
        /// </summary>
        internal static string Mishap_ColonyDisaster {
            get {
                return ResourceManager.GetString("Mishap_ColonyDisaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A civil disturbance was put down by the corporation..
        /// </summary>
        internal static string Mishap_ColonyDisturbance {
            get {
                return ResourceManager.GetString("Mishap_ColonyDisturbance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You outgrew the colony. You didn’t fit in anymore..
        /// </summary>
        internal static string Mishap_ColonyOutgrown {
            get {
                return ResourceManager.GetString("Mishap_ColonyOutgrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your ideas are revolutionary and unpopular - colonists attacked you and your settlement..
        /// </summary>
        internal static string Mishap_ColonyUnpopular {
            get {
                return ResourceManager.GetString("Mishap_ColonyUnpopular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Injured at work..
        /// </summary>
        internal static string Mishap_InjuredAtWork {
            get {
                return ResourceManager.GetString("Mishap_InjuredAtWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Injured on duty..
        /// </summary>
        internal static string Mishap_InjuredOnDuty {
            get {
                return ResourceManager.GetString("Mishap_InjuredOnDuty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New colonial leaders decided you and your crew were troublemakers..
        /// </summary>
        internal static string Mishap_NewColonyLeaders {
            get {
                return ResourceManager.GetString("Mishap_NewColonyLeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Commander.
        /// </summary>
        internal static string Rank_AreaCommander {
            get {
                return ResourceManager.GetString("Rank_AreaCommander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistant Driller.
        /// </summary>
        internal static string Rank_AssistantDriller {
            get {
                return ResourceManager.GetString("Rank_AssistantDriller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistant Operations Manager.
        /// </summary>
        internal static string Rank_AssistantOperationsManager {
            get {
                return ResourceManager.GetString("Rank_AssistantOperationsManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistant Team Leader.
        /// </summary>
        internal static string Rank_AssistantTeamLeader {
            get {
                return ResourceManager.GetString("Rank_AssistantTeamLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chief Ranger.
        /// </summary>
        internal static string Rank_ChiefRanger {
            get {
                return ResourceManager.GetString("Rank_ChiefRanger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colonial Administrator.
        /// </summary>
        internal static string Rank_ColonialAdministrator {
            get {
                return ResourceManager.GetString("Rank_ColonialAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colonist.
        /// </summary>
        internal static string Rank_Colonist {
            get {
                return ResourceManager.GetString("Rank_Colonist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Chief.
        /// </summary>
        internal static string Rank_DepartmentChief {
            get {
                return ResourceManager.GetString("Rank_DepartmentChief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deputy Chief Ranger.
        /// </summary>
        internal static string Rank_DeputyChiefRanger {
            get {
                return ResourceManager.GetString("Rank_DeputyChiefRanger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District Commander.
        /// </summary>
        internal static string Rank_DistrictCommander {
            get {
                return ResourceManager.GetString("Rank_DistrictCommander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driller.
        /// </summary>
        internal static string Rank_Driller {
            get {
                return ResourceManager.GetString("Rank_Driller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floorhand.
        /// </summary>
        internal static string Rank_Floorhand {
            get {
                return ResourceManager.GetString("Rank_Floorhand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Manager.
        /// </summary>
        internal static string Rank_GeneralManager {
            get {
                return ResourceManager.GetString("Rank_GeneralManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations Manager.
        /// </summary>
        internal static string Rank_OperationsManager {
            get {
                return ResourceManager.GetString("Rank_OperationsManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranger.
        /// </summary>
        internal static string Rank_Ranger {
            get {
                return ResourceManager.GetString("Rank_Ranger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roustabout.
        /// </summary>
        internal static string Rank_Roustabout {
            get {
                return ResourceManager.GetString("Rank_Roustabout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superintendant.
        /// </summary>
        internal static string Rank_Superintendant {
            get {
                return ResourceManager.GetString("Rank_Superintendant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor.
        /// </summary>
        internal static string Rank_Supervisor {
            get {
                return ResourceManager.GetString("Rank_Supervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Leader.
        /// </summary>
        internal static string Rank_TeamLeader {
            get {
                return ResourceManager.GetString("Rank_TeamLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolpusher.
        /// </summary>
        internal static string Rank_Toolpusher {
            get {
                return ResourceManager.GetString("Rank_Toolpusher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agriculture.
        /// </summary>
        internal static string Skill_Agriculture {
            get {
                return ResourceManager.GetString("Skill_Agriculture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loader.
        /// </summary>
        internal static string Skill_Loader {
            get {
                return ResourceManager.GetString("Skill_Loader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Android.
        /// </summary>
        internal static string Species_Android {
            get {
                return ResourceManager.GetString("Species_Android", resourceCulture);
            }
        }
    }
}
