//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace org.DownesWard.Traveller.CharacterGeneration.Cepheus.Hostile {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("org.DownesWard.Traveller.CharacterGeneration.Cepheus.Hostile.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distinguished Flying Cross.
        /// </summary>
        internal static string Benefit_DFC {
            get {
                return ResourceManager.GetString("Benefit_DFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elite Ticket.
        /// </summary>
        internal static string Benefit_EliteTicket {
            get {
                return ResourceManager.GetString("Benefit_EliteTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver Star.
        /// </summary>
        internal static string Benefit_SilverStar {
            get {
                return ResourceManager.GetString("Benefit_SilverStar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Ticket.
        /// </summary>
        internal static string Benefit_StandardTicket {
            get {
                return ResourceManager.GetString("Benefit_StandardTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star Envoy Club Member.
        /// </summary>
        internal static string Benefit_StarEnvoyClubMember {
            get {
                return ResourceManager.GetString("Benefit_StarEnvoyClubMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trauma Kit.
        /// </summary>
        internal static string Benefit_TraumaKit {
            get {
                return ResourceManager.GetString("Benefit_TraumaKit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colonist.
        /// </summary>
        internal static string Career_Colonist {
            get {
                return ResourceManager.GetString("Career_Colonist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commercial Spacer.
        /// </summary>
        internal static string Career_CommercialSpacer {
            get {
                return ResourceManager.GetString("Career_CommercialSpacer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate Agent.
        /// </summary>
        internal static string Career_CorporateAgent {
            get {
                return ResourceManager.GetString("Career_CorporateAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate Executive.
        /// </summary>
        internal static string Career_CorporateExecutive {
            get {
                return ResourceManager.GetString("Career_CorporateExecutive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marine.
        /// </summary>
        internal static string Career_Marine {
            get {
                return ResourceManager.GetString("Career_Marine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marshal.
        /// </summary>
        internal static string Career_Marshal {
            get {
                return ResourceManager.GetString("Career_Marshal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Military Spacer.
        /// </summary>
        internal static string Career_MilitarySpacer {
            get {
                return ResourceManager.GetString("Career_MilitarySpacer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physician.
        /// </summary>
        internal static string Career_Physician {
            get {
                return ResourceManager.GetString("Career_Physician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranger.
        /// </summary>
        internal static string Career_Ranger {
            get {
                return ResourceManager.GetString("Career_Ranger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rogue.
        /// </summary>
        internal static string Career_Rogue {
            get {
                return ResourceManager.GetString("Career_Rogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roughneck.
        /// </summary>
        internal static string Career_Roughneck {
            get {
                return ResourceManager.GetString("Career_Roughneck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scientist.
        /// </summary>
        internal static string Career_Scientist {
            get {
                return ResourceManager.GetString("Career_Scientist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey Scout.
        /// </summary>
        internal static string Career_SurveyScout {
            get {
                return ResourceManager.GetString("Career_SurveyScout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A corporate defection went wrong and you were wounded..
        /// </summary>
        internal static string Mishap_Agent1 {
            get {
                return ResourceManager.GetString("Mishap_Agent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your team was annihilated in a double-cross..
        /// </summary>
        internal static string Mishap_Agent2 {
            get {
                return ResourceManager.GetString("Mishap_Agent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A rival corporation killed members of your family and wounded you..
        /// </summary>
        internal static string Mishap_Agent3 {
            get {
                return ResourceManager.GetString("Mishap_Agent3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You learnt a secret about your employer and had to get out – fast..
        /// </summary>
        internal static string Mishap_Agent4 {
            get {
                return ResourceManager.GetString("Mishap_Agent4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An investigation uncovered government corruption, but you were forced to step down..
        /// </summary>
        internal static string Mishap_Agent5 {
            get {
                return ResourceManager.GetString("Mishap_Agent5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You failed to stop damage/disease/worker unrest at an Off-World outpost.
        /// </summary>
        internal static string Mishap_Agent6 {
            get {
                return ResourceManager.GetString("Mishap_Agent6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A colony accident left you injured..
        /// </summary>
        internal static string Mishap_ColonyAccident {
            get {
                return ResourceManager.GetString("Mishap_ColonyAccident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your colony is struck by disaster and you took some of the blame..
        /// </summary>
        internal static string Mishap_ColonyDisaster {
            get {
                return ResourceManager.GetString("Mishap_ColonyDisaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A civil disturbance was put down by the corporation..
        /// </summary>
        internal static string Mishap_ColonyDisturbance {
            get {
                return ResourceManager.GetString("Mishap_ColonyDisturbance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You outgrew the colony. You didn’t fit in anymore..
        /// </summary>
        internal static string Mishap_ColonyOutgrown {
            get {
                return ResourceManager.GetString("Mishap_ColonyOutgrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your ideas are revolutionary and unpopular - colonists attacked you and your settlement..
        /// </summary>
        internal static string Mishap_ColonyUnpopular {
            get {
                return ResourceManager.GetString("Mishap_ColonyUnpopular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caught smuggling illegal goods; you take the blame for your starline and are fired..
        /// </summary>
        internal static string Mishap_CommSpace1 {
            get {
                return ResourceManager.GetString("Mishap_CommSpace1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your starship is being scrapped and your crew retired..
        /// </summary>
        internal static string Mishap_CommSpace2 {
            get {
                return ResourceManager.GetString("Mishap_CommSpace2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your ship is destroyed and as the only survivor, you receive the blame..
        /// </summary>
        internal static string Mishap_CommSpace3 {
            get {
                return ResourceManager.GetString("Mishap_CommSpace3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Substance abuse destroys your career..
        /// </summary>
        internal static string Mishap_CommSpace4 {
            get {
                return ResourceManager.GetString("Mishap_CommSpace4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your ship is hijacked and your crew are all badly treated..
        /// </summary>
        internal static string Mishap_CommSpace5 {
            get {
                return ResourceManager.GetString("Mishap_CommSpace5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your private hit team messes up, implicating you in a dirty black ops strike..
        /// </summary>
        internal static string Mishap_Exec1 {
            get {
                return ResourceManager.GetString("Mishap_Exec1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A rival exec conducted a smear campaign against you, forcing you out of a job..
        /// </summary>
        internal static string Mishap_Exec2 {
            get {
                return ResourceManager.GetString("Mishap_Exec2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your orders to a mining outpost got a lot of the workers killed..
        /// </summary>
        internal static string Mishap_Exec3 {
            get {
                return ResourceManager.GetString("Mishap_Exec3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your ties to the underworld unravel – and you must leave the company..
        /// </summary>
        internal static string Mishap_Exec4 {
            get {
                return ResourceManager.GetString("Mishap_Exec4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The corporation rationalizes your department and you are ‘let go’..
        /// </summary>
        internal static string Mishap_Exec5 {
            get {
                return ResourceManager.GetString("Mishap_Exec5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Injured at work..
        /// </summary>
        internal static string Mishap_InjuredAtWork {
            get {
                return ResourceManager.GetString("Mishap_InjuredAtWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Injured on duty..
        /// </summary>
        internal static string Mishap_InjuredOnDuty {
            get {
                return ResourceManager.GetString("Mishap_InjuredOnDuty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During a mission you are captured and injured, when released you are honourably discharged..
        /// </summary>
        internal static string Mishap_Marine1 {
            get {
                return ResourceManager.GetString("Mishap_Marine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You argue with a senior officer who drives you out of the Marines..
        /// </summary>
        internal static string Mishap_Marine2 {
            get {
                return ResourceManager.GetString("Mishap_Marine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You were involved in an illegal operation, your conscience forces you to resign..
        /// </summary>
        internal static string Mishap_Marine5 {
            get {
                return ResourceManager.GetString("Mishap_Marine5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fighting hostile alien exomorphs, you save colonists, but are injured..
        /// </summary>
        internal static string Mishap_Marine6 {
            get {
                return ResourceManager.GetString("Mishap_Marine6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A riot or disturbance breaks out and several marshals are injured..
        /// </summary>
        internal static string Mishap_Marshal1 {
            get {
                return ResourceManager.GetString("Mishap_Marshal1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A deputy in the team works for a crime boss and sets you up.
        /// </summary>
        internal static string Mishap_Marshal2 {
            get {
                return ResourceManager.GetString("Mishap_Marshal2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You uncover a drugs ring at an outpost, but the manager is in on it and tries to have you killed..
        /// </summary>
        internal static string Mishap_Marshal3 {
            get {
                return ResourceManager.GetString("Mishap_Marshal3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A crime-lord bought off your team, forcing you to quit..
        /// </summary>
        internal static string Mishap_Marshal4 {
            get {
                return ResourceManager.GetString("Mishap_Marshal4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your team were killed in a fouled mission – and it was your fault..
        /// </summary>
        internal static string Mishap_Marshal5 {
            get {
                return ResourceManager.GetString("Mishap_Marshal5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An accident is blamed on you. Several crewmen were killed and you were discharged..
        /// </summary>
        internal static string Mishap_MilSpace1 {
            get {
                return ResourceManager.GetString("Mishap_MilSpace1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your starship attacks a civilian ship by mistake, tarnishing the careers of all the crew involved..
        /// </summary>
        internal static string Mishap_MilSpace2 {
            get {
                return ResourceManager.GetString("Mishap_MilSpace2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You argue with a senior officer who drives you out of Space Command..
        /// </summary>
        internal static string Mishap_MilSpace3 {
            get {
                return ResourceManager.GetString("Mishap_MilSpace3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A deadly alien infestation on-board ship that you survive is covered up by Space Command..
        /// </summary>
        internal static string Mishap_MilSpace5 {
            get {
                return ResourceManager.GetString("Mishap_MilSpace5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are wounded during an interstellar battle..
        /// </summary>
        internal static string Mishap_MilSpace6 {
            get {
                return ResourceManager.GetString("Mishap_MilSpace6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New colonial leaders decided you and your crew were troublemakers..
        /// </summary>
        internal static string Mishap_NewColonyLeaders {
            get {
                return ResourceManager.GetString("Mishap_NewColonyLeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your work is sabotaged and blackened by a third party..
        /// </summary>
        internal static string Mishap_Physician1 {
            get {
                return ResourceManager.GetString("Mishap_Physician1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A disaster with several casualties is blamed on you..
        /// </summary>
        internal static string Mishap_Physician2 {
            get {
                return ResourceManager.GetString("Mishap_Physician2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are involved in illegal research and rumours are spread about you. SOC reduced by 1..
        /// </summary>
        internal static string Mishap_Physician3 {
            get {
                return ResourceManager.GetString("Mishap_Physician3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You win a malpractice suit, but are forced to leave the profession..
        /// </summary>
        internal static string Mishap_Physician4 {
            get {
                return ResourceManager.GetString("Mishap_Physician4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are responsible for several deaths, serve several months in prison and are then released..
        /// </summary>
        internal static string Mishap_Physician5 {
            get {
                return ResourceManager.GetString("Mishap_Physician5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A rival corporation attacks your facility/operation..
        /// </summary>
        internal static string Mishap_Physician6 {
            get {
                return ResourceManager.GetString("Mishap_Physician6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attacked by dangerous alien exomorph..
        /// </summary>
        internal static string Mishap_RangerAttacked {
            get {
                return ResourceManager.GetString("Mishap_RangerAttacked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An expedition ends in disaster, people are killed..
        /// </summary>
        internal static string Mishap_RangerDisaster {
            get {
                return ResourceManager.GetString("Mishap_RangerDisaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You were lost in the wilderness and suffered exposure, after vehicle crash..
        /// </summary>
        internal static string Mishap_RangerLost {
            get {
                return ResourceManager.GetString("Mishap_RangerLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your team fails to rescue a high status casualty stranded in the wilds..
        /// </summary>
        internal static string Mishap_RangerRescueFailed {
            get {
                return ResourceManager.GetString("Mishap_RangerRescueFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your team locates a valiable resource, but a rival group siezes the site and claims it for their corporation..
        /// </summary>
        internal static string Mishap_RangerRivalGroup {
            get {
                return ResourceManager.GetString("Mishap_RangerRivalGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A job goes horribly wrong, you get the blame..
        /// </summary>
        internal static string Mishap_Rogue1 {
            get {
                return ResourceManager.GetString("Mishap_Rogue1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrested and convicted..
        /// </summary>
        internal static string Mishap_Rogue2 {
            get {
                return ResourceManager.GetString("Mishap_Rogue2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criminal successes are followed by violent retaliations from a rival gang..
        /// </summary>
        internal static string Mishap_Rogue3 {
            get {
                return ResourceManager.GetString("Mishap_Rogue3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your crew make a bitter enemy, a police officer, and must lay low..
        /// </summary>
        internal static string Mishap_Rogue4 {
            get {
                return ResourceManager.GetString("Mishap_Rogue4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A gang rival forces you out of the organization..
        /// </summary>
        internal static string Mishap_Rogue5 {
            get {
                return ResourceManager.GetString("Mishap_Rogue5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Injured in a gang battle..
        /// </summary>
        internal static string Mishap_Rogue6 {
            get {
                return ResourceManager.GetString("Mishap_Rogue6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An accident is blamed on you, and you are fired..
        /// </summary>
        internal static string Mishap_RoughneckAccident {
            get {
                return ResourceManager.GetString("Mishap_RoughneckAccident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You clash with your boss, who makes life too tough for you to continue..
        /// </summary>
        internal static string Mishap_RoughneckBadBoss {
            get {
                return ResourceManager.GetString("Mishap_RoughneckBadBoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are fired on a trumped up charge, just for speaking up for your comrades..
        /// </summary>
        internal static string Mishap_RoughneckFired {
            get {
                return ResourceManager.GetString("Mishap_RoughneckFired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You suffer from illness caused by your work..
        /// </summary>
        internal static string Mishap_RoughneckIllness {
            get {
                return ResourceManager.GetString("Mishap_RoughneckIllness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your work is sabotaged and blackened by a third party..
        /// </summary>
        internal static string Mishap_Science1 {
            get {
                return ResourceManager.GetString("Mishap_Science1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A rival corp attempts to kidnap you and steal your research; you must flee..
        /// </summary>
        internal static string Mishap_Science2 {
            get {
                return ResourceManager.GetString("Mishap_Science2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are involved in illegal research and rumours are spread about you. Soc reduced by 1..
        /// </summary>
        internal static string Mishap_Science3 {
            get {
                return ResourceManager.GetString("Mishap_Science3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An expedition goes wrong, resulting in several deaths..
        /// </summary>
        internal static string Mishap_Science4 {
            get {
                return ResourceManager.GetString("Mishap_Science4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your experiments have unpredictable results, and the project is shut down for good..
        /// </summary>
        internal static string Mishap_Science5 {
            get {
                return ResourceManager.GetString("Mishap_Science5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rival corporation attacks your facility/operation..
        /// </summary>
        internal static string Mishap_Science6 {
            get {
                return ResourceManager.GetString("Mishap_Science6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crash on remote planet..
        /// </summary>
        internal static string Mishap_Scout2 {
            get {
                return ResourceManager.GetString("Mishap_Scout2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your team locates a valiable resource, but a rival group siezes the site and claims it for their
        ///corporation..
        /// </summary>
        internal static string Mishap_Scout3 {
            get {
                return ResourceManager.GetString("Mishap_Scout3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An expedition ends in disaster and you are blamed for it..
        /// </summary>
        internal static string Mishap_Scout4 {
            get {
                return ResourceManager.GetString("Mishap_Scout4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attacked by dangerous alien exomorph..
        /// </summary>
        internal static string Mishap_Scout5 {
            get {
                return ResourceManager.GetString("Mishap_Scout5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are sent to a location by an corporate exec, but he knows it is dangerous, and your crew are
        ///badly injured. He threatens to blame everything on you..
        /// </summary>
        internal static string Mishap_Scout6 {
            get {
                return ResourceManager.GetString("Mishap_Scout6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Born on an Off-world colony.
        /// </summary>
        internal static string Msg_BornOffWorld {
            get {
                return ResourceManager.GetString("Msg_BornOffWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Born on Earth.
        /// </summary>
        internal static string Msg_BornOnEarth {
            get {
                return ResourceManager.GetString("Msg_BornOnEarth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Officer.
        /// </summary>
        internal static string Rank_1stOfficer {
            get {
                return ResourceManager.GetString("Rank_1stOfficer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Officer.
        /// </summary>
        internal static string Rank_2ndOfficer {
            get {
                return ResourceManager.GetString("Rank_2ndOfficer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third Officer.
        /// </summary>
        internal static string Rank_3rdOfficer {
            get {
                return ResourceManager.GetString("Rank_3rdOfficer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fourth Officer.
        /// </summary>
        internal static string Rank_4thOfficer {
            get {
                return ResourceManager.GetString("Rank_4thOfficer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent.
        /// </summary>
        internal static string Rank_Agent {
            get {
                return ResourceManager.GetString("Rank_Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airman.
        /// </summary>
        internal static string Rank_Airman {
            get {
                return ResourceManager.GetString("Rank_Airman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airman First Class.
        /// </summary>
        internal static string Rank_AirmanFirstClass {
            get {
                return ResourceManager.GetString("Rank_AirmanFirstClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Commander.
        /// </summary>
        internal static string Rank_AreaCommander {
            get {
                return ResourceManager.GetString("Rank_AreaCommander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistant Chief.
        /// </summary>
        internal static string Rank_AssistantChief {
            get {
                return ResourceManager.GetString("Rank_AssistantChief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistant Director.
        /// </summary>
        internal static string Rank_AssistantDirector {
            get {
                return ResourceManager.GetString("Rank_AssistantDirector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistant Division Chief.
        /// </summary>
        internal static string Rank_AssistantDivisionChief {
            get {
                return ResourceManager.GetString("Rank_AssistantDivisionChief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistant Driller.
        /// </summary>
        internal static string Rank_AssistantDriller {
            get {
                return ResourceManager.GetString("Rank_AssistantDriller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistant Operations Manager.
        /// </summary>
        internal static string Rank_AssistantOperationsManager {
            get {
                return ResourceManager.GetString("Rank_AssistantOperationsManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistant Project Leader.
        /// </summary>
        internal static string Rank_AssistantProjectLeader {
            get {
                return ResourceManager.GetString("Rank_AssistantProjectLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistant Team Leader.
        /// </summary>
        internal static string Rank_AssistantTeamLeader {
            get {
                return ResourceManager.GetString("Rank_AssistantTeamLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain.
        /// </summary>
        internal static string Rank_Captain {
            get {
                return ResourceManager.GetString("Rank_Captain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chief Deputy.
        /// </summary>
        internal static string Rank_ChiefDeputy {
            get {
                return ResourceManager.GetString("Rank_ChiefDeputy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chief Ranger.
        /// </summary>
        internal static string Rank_ChiefRanger {
            get {
                return ResourceManager.GetString("Rank_ChiefRanger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cholo.
        /// </summary>
        internal static string Rank_Cholo {
            get {
                return ResourceManager.GetString("Rank_Cholo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colonel.
        /// </summary>
        internal static string Rank_Colonel {
            get {
                return ResourceManager.GetString("Rank_Colonel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colonial Administrator.
        /// </summary>
        internal static string Rank_ColonialAdministrator {
            get {
                return ResourceManager.GetString("Rank_ColonialAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colonist.
        /// </summary>
        internal static string Rank_Colonist {
            get {
                return ResourceManager.GetString("Rank_Colonist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultant.
        /// </summary>
        internal static string Rank_Consultant {
            get {
                return ResourceManager.GetString("Rank_Consultant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporal.
        /// </summary>
        internal static string Rank_Corporal {
            get {
                return ResourceManager.GetString("Rank_Corporal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crewman.
        /// </summary>
        internal static string Rank_Crewman {
            get {
                return ResourceManager.GetString("Rank_Crewman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Chief.
        /// </summary>
        internal static string Rank_DepartmentChief {
            get {
                return ResourceManager.GetString("Rank_DepartmentChief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deputy.
        /// </summary>
        internal static string Rank_Deputy {
            get {
                return ResourceManager.GetString("Rank_Deputy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deputy Chief Ranger.
        /// </summary>
        internal static string Rank_DeputyChiefRanger {
            get {
                return ResourceManager.GetString("Rank_DeputyChiefRanger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deputy Science Leader.
        /// </summary>
        internal static string Rank_DeputyScienceLeader {
            get {
                return ResourceManager.GetString("Rank_DeputyScienceLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Director.
        /// </summary>
        internal static string Rank_Director {
            get {
                return ResourceManager.GetString("Rank_Director", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District Commander.
        /// </summary>
        internal static string Rank_DistrictCommander {
            get {
                return ResourceManager.GetString("Rank_DistrictCommander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division Chief.
        /// </summary>
        internal static string Rank_DivisionChief {
            get {
                return ResourceManager.GetString("Rank_DivisionChief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor.
        /// </summary>
        internal static string Rank_Doctor {
            get {
                return ResourceManager.GetString("Rank_Doctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driller.
        /// </summary>
        internal static string Rank_Driller {
            get {
                return ResourceManager.GetString("Rank_Driller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executive Consultant.
        /// </summary>
        internal static string Rank_ExecutiveConsultant {
            get {
                return ResourceManager.GetString("Rank_ExecutiveConsultant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executive Senior Vice President.
        /// </summary>
        internal static string Rank_ExecutiveSeniorVicePresident {
            get {
                return ResourceManager.GetString("Rank_ExecutiveSeniorVicePresident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floorhand.
        /// </summary>
        internal static string Rank_Floorhand {
            get {
                return ResourceManager.GetString("Rank_Floorhand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string Rank_General {
            get {
                return ResourceManager.GetString("Rank_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Manager.
        /// </summary>
        internal static string Rank_GeneralManager {
            get {
                return ResourceManager.GetString("Rank_GeneralManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gunnery Sergeant.
        /// </summary>
        internal static string Rank_GunnerySergeant {
            get {
                return ResourceManager.GetString("Rank_GunnerySergeant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intern.
        /// </summary>
        internal static string Rank_Intern {
            get {
                return ResourceManager.GetString("Rank_Intern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Junior Doctor.
        /// </summary>
        internal static string Rank_JuniorDoctor {
            get {
                return ResourceManager.GetString("Rank_JuniorDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lance Corporal.
        /// </summary>
        internal static string Rank_LanceCorporal {
            get {
                return ResourceManager.GetString("Rank_LanceCorporal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lieutenant.
        /// </summary>
        internal static string Rank_Lieutenant {
            get {
                return ResourceManager.GetString("Rank_Lieutenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lt. Colonel.
        /// </summary>
        internal static string Rank_LtColonel {
            get {
                return ResourceManager.GetString("Rank_LtColonel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major.
        /// </summary>
        internal static string Rank_Major {
            get {
                return ResourceManager.GetString("Rank_Major", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marshal.
        /// </summary>
        internal static string Rank_Marshal {
            get {
                return ResourceManager.GetString("Rank_Marshal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Sergeant.
        /// </summary>
        internal static string Rank_MasterSergeant {
            get {
                return ResourceManager.GetString("Rank_MasterSergeant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Student.
        /// </summary>
        internal static string Rank_MedicalStudent {
            get {
                return ResourceManager.GetString("Rank_MedicalStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission Chief.
        /// </summary>
        internal static string Rank_MissionChief {
            get {
                return ResourceManager.GetString("Rank_MissionChief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission Specialist.
        /// </summary>
        internal static string Rank_MissionSpecialist {
            get {
                return ResourceManager.GetString("Rank_MissionSpecialist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations Chief.
        /// </summary>
        internal static string Rank_OperationsChief {
            get {
                return ResourceManager.GetString("Rank_OperationsChief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations Manager.
        /// </summary>
        internal static string Rank_OperationsManager {
            get {
                return ResourceManager.GetString("Rank_OperationsManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to President.
        /// </summary>
        internal static string Rank_President {
            get {
                return ResourceManager.GetString("Rank_President", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        internal static string Rank_Private {
            get {
                return ResourceManager.GetString("Rank_Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Leader.
        /// </summary>
        internal static string Rank_ProjectLeader {
            get {
                return ResourceManager.GetString("Rank_ProjectLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranger.
        /// </summary>
        internal static string Rank_Ranger {
            get {
                return ResourceManager.GetString("Rank_Ranger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Researcher.
        /// </summary>
        internal static string Rank_Researcher {
            get {
                return ResourceManager.GetString("Rank_Researcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Hand.
        /// </summary>
        internal static string Rank_RightHand {
            get {
                return ResourceManager.GetString("Rank_RightHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roustabout.
        /// </summary>
        internal static string Rank_Roustabout {
            get {
                return ResourceManager.GetString("Rank_Roustabout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Science Leader.
        /// </summary>
        internal static string Rank_ScienceLeader {
            get {
                return ResourceManager.GetString("Rank_ScienceLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scientist.
        /// </summary>
        internal static string Rank_Scientist {
            get {
                return ResourceManager.GetString("Rank_Scientist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scout.
        /// </summary>
        internal static string Rank_Scout {
            get {
                return ResourceManager.GetString("Rank_Scout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senior Agent.
        /// </summary>
        internal static string Rank_SeniorAgent {
            get {
                return ResourceManager.GetString("Rank_SeniorAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senior Airman.
        /// </summary>
        internal static string Rank_SeniorAirman {
            get {
                return ResourceManager.GetString("Rank_SeniorAirman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senior Captain.
        /// </summary>
        internal static string Rank_SeniorCaptain {
            get {
                return ResourceManager.GetString("Rank_SeniorCaptain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senior Consultant.
        /// </summary>
        internal static string Rank_SeniorConsultant {
            get {
                return ResourceManager.GetString("Rank_SeniorConsultant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senior Deputy.
        /// </summary>
        internal static string Rank_SeniorDeputy {
            get {
                return ResourceManager.GetString("Rank_SeniorDeputy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senior Executive Vice President.
        /// </summary>
        internal static string Rank_SeniorExecutiveVicePresident {
            get {
                return ResourceManager.GetString("Rank_SeniorExecutiveVicePresident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senior Mission Specialist.
        /// </summary>
        internal static string Rank_SeniorMissionSpecialist {
            get {
                return ResourceManager.GetString("Rank_SeniorMissionSpecialist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senior Scientist.
        /// </summary>
        internal static string Rank_SeniorScientist {
            get {
                return ResourceManager.GetString("Rank_SeniorScientist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senior Scout.
        /// </summary>
        internal static string Rank_SeniorScout {
            get {
                return ResourceManager.GetString("Rank_SeniorScout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senior Vice President.
        /// </summary>
        internal static string Rank_SeniorVicePresident {
            get {
                return ResourceManager.GetString("Rank_SeniorVicePresident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sergeant.
        /// </summary>
        internal static string Rank_Sergeant {
            get {
                return ResourceManager.GetString("Rank_Sergeant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soldier.
        /// </summary>
        internal static string Rank_Soldier {
            get {
                return ResourceManager.GetString("Rank_Soldier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Sergeant.
        /// </summary>
        internal static string Rank_StaffSergeant {
            get {
                return ResourceManager.GetString("Rank_StaffSergeant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superintendant.
        /// </summary>
        internal static string Rank_Superintendant {
            get {
                return ResourceManager.GetString("Rank_Superintendant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor.
        /// </summary>
        internal static string Rank_Supervisor {
            get {
                return ResourceManager.GetString("Rank_Supervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisory Deputy.
        /// </summary>
        internal static string Rank_SupervisoryDeputy {
            get {
                return ResourceManager.GetString("Rank_SupervisoryDeputy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Leader.
        /// </summary>
        internal static string Rank_TeamLeader {
            get {
                return ResourceManager.GetString("Rank_TeamLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Sergeant.
        /// </summary>
        internal static string Rank_TechnicalSergeant {
            get {
                return ResourceManager.GetString("Rank_TechnicalSergeant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolpusher.
        /// </summary>
        internal static string Rank_Toolpusher {
            get {
                return ResourceManager.GetString("Rank_Toolpusher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veteran.
        /// </summary>
        internal static string Rank_Veteran {
            get {
                return ResourceManager.GetString("Rank_Veteran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vice President.
        /// </summary>
        internal static string Rank_VicePresident {
            get {
                return ResourceManager.GetString("Rank_VicePresident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agriculture.
        /// </summary>
        internal static string Skill_Agriculture {
            get {
                return ResourceManager.GetString("Skill_Agriculture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Skills.
        /// </summary>
        internal static string Skill_Background {
            get {
                return ResourceManager.GetString("Skill_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blade Combat.
        /// </summary>
        internal static string Skill_BladeCombat {
            get {
                return ResourceManager.GetString("Skill_BladeCombat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gun Combat.
        /// </summary>
        internal static string Skill_GunCombat {
            get {
                return ResourceManager.GetString("Skill_GunCombat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investigate.
        /// </summary>
        internal static string Skill_Investigate {
            get {
                return ResourceManager.GetString("Skill_Investigate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loader.
        /// </summary>
        internal static string Skill_Loader {
            get {
                return ResourceManager.GetString("Skill_Loader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mining.
        /// </summary>
        internal static string Skill_Mining {
            get {
                return ResourceManager.GetString("Skill_Mining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        internal static string Skill_Security {
            get {
                return ResourceManager.GetString("Skill_Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Android.
        /// </summary>
        internal static string Species_Android {
            get {
                return ResourceManager.GetString("Species_Android", resourceCulture);
            }
        }
    }
}
