//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace org.DownesWard.Traveller.AlienCreation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("org.DownesWard.Traveller.AlienCreation.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dual-purpose (Manipulation and Locomotion).
        /// </summary>
        internal static string Limb_DualPurpose {
            get {
                return ResourceManager.GetString("Limb_DualPurpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fins.
        /// </summary>
        internal static string Limb_Fins {
            get {
                return ResourceManager.GetString("Limb_Fins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legs.
        /// </summary>
        internal static string Limb_Legs {
            get {
                return ResourceManager.GetString("Limb_Legs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manipulation.
        /// </summary>
        internal static string Limb_Manipulation {
            get {
                return ResourceManager.GetString("Limb_Manipulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wings.
        /// </summary>
        internal static string Limb_Wings {
            get {
                return ResourceManager.GetString("Limb_Wings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acid Resistance.
        /// </summary>
        internal static string Trait_AcidResistance {
            get {
                return ResourceManager.GetString("Trait_AcidResistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acid Vulnerability.
        /// </summary>
        internal static string Trait_AcidVulnerability {
            get {
                return ResourceManager.GetString("Trait_AcidVulnerability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alertness.
        /// </summary>
        internal static string Trait_Alertness {
            get {
                return ResourceManager.GetString("Trait_Alertness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude Adaption.
        /// </summary>
        internal static string Trait_AltitudeAdaption {
            get {
                return ResourceManager.GetString("Trait_AltitudeAdaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anti-Psionic.
        /// </summary>
        internal static string Trait_AntiPsionic {
            get {
                return ResourceManager.GetString("Trait_AntiPsionic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Athletic.
        /// </summary>
        internal static string Trait_Athletic {
            get {
                return ResourceManager.GetString("Trait_Athletic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad First Impression.
        /// </summary>
        internal static string Trait_BadFirstImpression {
            get {
                return ResourceManager.GetString("Trait_BadFirstImpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blind-Fighter.
        /// </summary>
        internal static string Trait_BlindFighter {
            get {
                return ResourceManager.GetString("Trait_BlindFighter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed Book.
        /// </summary>
        internal static string Trait_ClosedBook {
            get {
                return ResourceManager.GetString("Trait_ClosedBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eidetic Memory.
        /// </summary>
        internal static string Trait_EideticMemory {
            get {
                return ResourceManager.GetString("Trait_EideticMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast Talker.
        /// </summary>
        internal static string Trait_FastTalker {
            get {
                return ResourceManager.GetString("Trait_FastTalker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gearhead.
        /// </summary>
        internal static string Trait_Gearhead {
            get {
                return ResourceManager.GetString("Trait_Gearhead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good First Impression.
        /// </summary>
        internal static string Trait_GoodFirstImpression {
            get {
                return ResourceManager.GetString("Trait_GoodFirstImpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haggler.
        /// </summary>
        internal static string Trait_Haggler {
            get {
                return ResourceManager.GetString("Trait_Haggler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interrogator.
        /// </summary>
        internal static string Trait_Interrogator {
            get {
                return ResourceManager.GetString("Trait_Interrogator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intolerant.
        /// </summary>
        internal static string Trait_Intolerant {
            get {
                return ResourceManager.GetString("Trait_Intolerant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natural Advocate.
        /// </summary>
        internal static string Trait_NaturalAdvocate {
            get {
                return ResourceManager.GetString("Trait_NaturalAdvocate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natural Born Leader.
        /// </summary>
        internal static string Trait_NaturalBornLeader {
            get {
                return ResourceManager.GetString("Trait_NaturalBornLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natural Compass.
        /// </summary>
        internal static string Trait_NaturalCompass {
            get {
                return ResourceManager.GetString("Trait_NaturalCompass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naturally Honest.
        /// </summary>
        internal static string Trait_NaturallyHonest {
            get {
                return ResourceManager.GetString("Trait_NaturallyHonest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natural Pilot.
        /// </summary>
        internal static string Trait_NaturalPilot {
            get {
                return ResourceManager.GetString("Trait_NaturalPilot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natural Survivalist.
        /// </summary>
        internal static string Trait_NaturalSurvivalist {
            get {
                return ResourceManager.GetString("Trait_NaturalSurvivalist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natural Thief.
        /// </summary>
        internal static string Trait_NaturalThief {
            get {
                return ResourceManager.GetString("Trait_NaturalThief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overly Aggressive.
        /// </summary>
        internal static string Trait_OverlyAggressive {
            get {
                return ResourceManager.GetString("Trait_OverlyAggressive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Psionic.
        /// </summary>
        internal static string Trait_Psionic {
            get {
                return ResourceManager.GetString("Trait_Psionic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Racial Defence.
        /// </summary>
        internal static string Trait_RacialDefence {
            get {
                return ResourceManager.GetString("Trait_RacialDefence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Racial Enemy.
        /// </summary>
        internal static string Trait_RacialEnemy {
            get {
                return ResourceManager.GetString("Trait_RacialEnemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Racial Phobia.
        /// </summary>
        internal static string Trait_RacialPhobia {
            get {
                return ResourceManager.GetString("Trait_RacialPhobia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Racial Weapon.
        /// </summary>
        internal static string Trait_RacialWeapon {
            get {
                return ResourceManager.GetString("Trait_RacialWeapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referee&apos;s Choice.
        /// </summary>
        internal static string Trait_RefereesChoice {
            get {
                return ResourceManager.GetString("Trait_RefereesChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stealthy.
        /// </summary>
        internal static string Trait_Stealthy {
            get {
                return ResourceManager.GetString("Trait_Stealthy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trustworthy.
        /// </summary>
        internal static string Trait_Trustworthy {
            get {
                return ResourceManager.GetString("Trait_Trustworthy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Well-Travelled.
        /// </summary>
        internal static string Trait_WellTravelled {
            get {
                return ResourceManager.GetString("Trait_WellTravelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xeno-Empathy.
        /// </summary>
        internal static string Trait_XenoEmpathy {
            get {
                return ResourceManager.GetString("Trait_XenoEmpathy", resourceCulture);
            }
        }
    }
}
