//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace org.DownesWard.Traveller.AlienCreation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("org.DownesWard.Traveller.AlienCreation.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acute Hearing.
        /// </summary>
        internal static string Hearing_AcuteHearing {
            get {
                return ResourceManager.GetString("Hearing_AcuteHearing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deaf.
        /// </summary>
        internal static string Hearing_Deaf {
            get {
                return ResourceManager.GetString("Hearing_Deaf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poor Hearing.
        /// </summary>
        internal static string Hearing_PoorHearing {
            get {
                return ResourceManager.GetString("Hearing_PoorHearing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dual-purpose (Manipulation and Locomotion).
        /// </summary>
        internal static string Limb_DualPurpose {
            get {
                return ResourceManager.GetString("Limb_DualPurpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fins.
        /// </summary>
        internal static string Limb_Fins {
            get {
                return ResourceManager.GetString("Limb_Fins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legs.
        /// </summary>
        internal static string Limb_Legs {
            get {
                return ResourceManager.GetString("Limb_Legs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manipulation.
        /// </summary>
        internal static string Limb_Manipulation {
            get {
                return ResourceManager.GetString("Limb_Manipulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wings.
        /// </summary>
        internal static string Limb_Wings {
            get {
                return ResourceManager.GetString("Limb_Wings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anosmic.
        /// </summary>
        internal static string Scent_Anosmic {
            get {
                return ResourceManager.GetString("Scent_Anosmic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poor Scent.
        /// </summary>
        internal static string Scent_PoorScent {
            get {
                return ResourceManager.GetString("Scent_PoorScent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scent.
        /// </summary>
        internal static string Scent_Scent {
            get {
                return ResourceManager.GetString("Scent_Scent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organic Radio Communications.
        /// </summary>
        internal static string Sense_OrganicRadioCommunications {
            get {
                return ResourceManager.GetString("Sense_OrganicRadioCommunications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telepathy.
        /// </summary>
        internal static string Sense_Telepathy {
            get {
                return ResourceManager.GetString("Sense_Telepathy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telepathy, Limited.
        /// </summary>
        internal static string Sense_TelepathyLimited {
            get {
                return ResourceManager.GetString("Sense_TelepathyLimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vibration Sense.
        /// </summary>
        internal static string Sense_VibrationSense {
            get {
                return ResourceManager.GetString("Sense_VibrationSense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acid Resistance.
        /// </summary>
        internal static string Trait_AcidResistance {
            get {
                return ResourceManager.GetString("Trait_AcidResistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acid Vulnerability.
        /// </summary>
        internal static string Trait_AcidVulnerability {
            get {
                return ResourceManager.GetString("Trait_AcidVulnerability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alertness.
        /// </summary>
        internal static string Trait_Alertness {
            get {
                return ResourceManager.GetString("Trait_Alertness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude Adaption.
        /// </summary>
        internal static string Trait_AltitudeAdaption {
            get {
                return ResourceManager.GetString("Trait_AltitudeAdaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anti-Psionic.
        /// </summary>
        internal static string Trait_AntiPsionic {
            get {
                return ResourceManager.GetString("Trait_AntiPsionic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armoured.
        /// </summary>
        internal static string Trait_Armoured {
            get {
                return ResourceManager.GetString("Trait_Armoured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Athletic.
        /// </summary>
        internal static string Trait_Athletic {
            get {
                return ResourceManager.GetString("Trait_Athletic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad First Impression.
        /// </summary>
        internal static string Trait_BadFirstImpression {
            get {
                return ResourceManager.GetString("Trait_BadFirstImpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blind-Fighter.
        /// </summary>
        internal static string Trait_BlindFighter {
            get {
                return ResourceManager.GetString("Trait_BlindFighter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caste.
        /// </summary>
        internal static string Trait_Caste {
            get {
                return ResourceManager.GetString("Trait_Caste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charisma.
        /// </summary>
        internal static string Trait_Charisma {
            get {
                return ResourceManager.GetString("Trait_Charisma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed Book.
        /// </summary>
        internal static string Trait_ClosedBook {
            get {
                return ResourceManager.GetString("Trait_ClosedBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cold Endurance.
        /// </summary>
        internal static string Trait_ColdEndurance {
            get {
                return ResourceManager.GetString("Trait_ColdEndurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cold Resistance.
        /// </summary>
        internal static string Trait_ColdResistance {
            get {
                return ResourceManager.GetString("Trait_ColdResistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cold Vulnerability.
        /// </summary>
        internal static string Trait_ColdVulnerability {
            get {
                return ResourceManager.GetString("Trait_ColdVulnerability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eidetic Memory.
        /// </summary>
        internal static string Trait_EideticMemory {
            get {
                return ResourceManager.GetString("Trait_EideticMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electricity Resistance.
        /// </summary>
        internal static string Trait_ElectricityResistance {
            get {
                return ResourceManager.GetString("Trait_ElectricityResistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engineered.
        /// </summary>
        internal static string Trait_Engineered {
            get {
                return ResourceManager.GetString("Trait_Engineered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast Healing.
        /// </summary>
        internal static string Trait_FastHealing {
            get {
                return ResourceManager.GetString("Trait_FastHealing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast Talker.
        /// </summary>
        internal static string Trait_FastTalker {
            get {
                return ResourceManager.GetString("Trait_FastTalker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire Resistance.
        /// </summary>
        internal static string Trait_FireResistance {
            get {
                return ResourceManager.GetString("Trait_FireResistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire Vulnerability.
        /// </summary>
        internal static string Trait_FireVulnerability {
            get {
                return ResourceManager.GetString("Trait_FireVulnerability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flyer.
        /// </summary>
        internal static string Trait_Flyer {
            get {
                return ResourceManager.GetString("Trait_Flyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fragile.
        /// </summary>
        internal static string Trait_Fragile {
            get {
                return ResourceManager.GetString("Trait_Fragile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frightful Presence.
        /// </summary>
        internal static string Trait_FrightfulPresence {
            get {
                return ResourceManager.GetString("Trait_FrightfulPresence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gearhead.
        /// </summary>
        internal static string Trait_Gearhead {
            get {
                return ResourceManager.GetString("Trait_Gearhead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good First Impression.
        /// </summary>
        internal static string Trait_GoodFirstImpression {
            get {
                return ResourceManager.GetString("Trait_GoodFirstImpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haggler.
        /// </summary>
        internal static string Trait_Haggler {
            get {
                return ResourceManager.GetString("Trait_Haggler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heat Endurance.
        /// </summary>
        internal static string Trait_HeatEndurance {
            get {
                return ResourceManager.GetString("Trait_HeatEndurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hibernation.
        /// </summary>
        internal static string Trait_Hibernation {
            get {
                return ResourceManager.GetString("Trait_Hibernation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improved Grab.
        /// </summary>
        internal static string Trait_ImprovedGrab {
            get {
                return ResourceManager.GetString("Trait_ImprovedGrab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improved Grab: Constrict.
        /// </summary>
        internal static string Trait_ImprovedGrabConstrict {
            get {
                return ResourceManager.GetString("Trait_ImprovedGrabConstrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improved Grab: Entangle.
        /// </summary>
        internal static string Trait_ImprovedGrabEntangle {
            get {
                return ResourceManager.GetString("Trait_ImprovedGrabEntangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improved Reach.
        /// </summary>
        internal static string Trait_ImprovedReach {
            get {
                return ResourceManager.GetString("Trait_ImprovedReach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interrogator.
        /// </summary>
        internal static string Trait_Interrogator {
            get {
                return ResourceManager.GetString("Trait_Interrogator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intolerant.
        /// </summary>
        internal static string Trait_Intolerant {
            get {
                return ResourceManager.GetString("Trait_Intolerant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natural Advocate.
        /// </summary>
        internal static string Trait_NaturalAdvocate {
            get {
                return ResourceManager.GetString("Trait_NaturalAdvocate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natural Born Leader.
        /// </summary>
        internal static string Trait_NaturalBornLeader {
            get {
                return ResourceManager.GetString("Trait_NaturalBornLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natural Compass.
        /// </summary>
        internal static string Trait_NaturalCompass {
            get {
                return ResourceManager.GetString("Trait_NaturalCompass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naturally Honest.
        /// </summary>
        internal static string Trait_NaturallyHonest {
            get {
                return ResourceManager.GetString("Trait_NaturallyHonest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natural Pilot.
        /// </summary>
        internal static string Trait_NaturalPilot {
            get {
                return ResourceManager.GetString("Trait_NaturalPilot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natural Survivalist.
        /// </summary>
        internal static string Trait_NaturalSurvivalist {
            get {
                return ResourceManager.GetString("Trait_NaturalSurvivalist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natural Thief.
        /// </summary>
        internal static string Trait_NaturalThief {
            get {
                return ResourceManager.GetString("Trait_NaturalThief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natural Weapons.
        /// </summary>
        internal static string Trait_NaturalWeapons {
            get {
                return ResourceManager.GetString("Trait_NaturalWeapons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Fine Manipulators.
        /// </summary>
        internal static string Trait_NoFineManipulators {
            get {
                return ResourceManager.GetString("Trait_NoFineManipulators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Land Movement.
        /// </summary>
        internal static string Trait_NoLandMovement {
            get {
                return ResourceManager.GetString("Trait_NoLandMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Vocal Cords.
        /// </summary>
        internal static string Trait_NoVocalCords {
            get {
                return ResourceManager.GetString("Trait_NoVocalCords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overly Aggressive.
        /// </summary>
        internal static string Trait_OverlyAggressive {
            get {
                return ResourceManager.GetString("Trait_OverlyAggressive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pleasant Odor.
        /// </summary>
        internal static string Trait_PleasantOdor {
            get {
                return ResourceManager.GetString("Trait_PleasantOdor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poisonous.
        /// </summary>
        internal static string Trait_Poisonous {
            get {
                return ResourceManager.GetString("Trait_Poisonous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Psionic.
        /// </summary>
        internal static string Trait_Psionic {
            get {
                return ResourceManager.GetString("Trait_Psionic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Racial Defence.
        /// </summary>
        internal static string Trait_RacialDefence {
            get {
                return ResourceManager.GetString("Trait_RacialDefence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Racial Enemy.
        /// </summary>
        internal static string Trait_RacialEnemy {
            get {
                return ResourceManager.GetString("Trait_RacialEnemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Racial Phobia.
        /// </summary>
        internal static string Trait_RacialPhobia {
            get {
                return ResourceManager.GetString("Trait_RacialPhobia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Racial Weapon.
        /// </summary>
        internal static string Trait_RacialWeapon {
            get {
                return ResourceManager.GetString("Trait_RacialWeapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radiaton Resistance.
        /// </summary>
        internal static string Trait_RadiatonResistance {
            get {
                return ResourceManager.GetString("Trait_RadiatonResistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referee&apos;s Choice.
        /// </summary>
        internal static string Trait_RefereesChoice {
            get {
                return ResourceManager.GetString("Trait_RefereesChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regeneration.
        /// </summary>
        internal static string Trait_Regeneration {
            get {
                return ResourceManager.GetString("Trait_Regeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resistant to Disease.
        /// </summary>
        internal static string Trait_ResistantToDisease {
            get {
                return ResourceManager.GetString("Trait_ResistantToDisease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resistant to Fear.
        /// </summary>
        internal static string Trait_ResistantToFear {
            get {
                return ResourceManager.GetString("Trait_ResistantToFear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resistant to Poisons.
        /// </summary>
        internal static string Trait_ResistantToPoisons {
            get {
                return ResourceManager.GetString("Trait_ResistantToPoisons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resistant to Psionics.
        /// </summary>
        internal static string Trait_ResistantToPsionics {
            get {
                return ResourceManager.GetString("Trait_ResistantToPsionics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spitting Attack.
        /// </summary>
        internal static string Trait_SpittingAttack {
            get {
                return ResourceManager.GetString("Trait_SpittingAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stealthy.
        /// </summary>
        internal static string Trait_Stealthy {
            get {
                return ResourceManager.GetString("Trait_Stealthy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trustworthy.
        /// </summary>
        internal static string Trait_Trustworthy {
            get {
                return ResourceManager.GetString("Trait_Trustworthy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unusual Hand Structure.
        /// </summary>
        internal static string Trait_UnusualHandStructure {
            get {
                return ResourceManager.GetString("Trait_UnusualHandStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unusual Life Support Requirements, Major.
        /// </summary>
        internal static string Trait_UnusualLifeSupportRequirementsMajor {
            get {
                return ResourceManager.GetString("Trait_UnusualLifeSupportRequirementsMajor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unusual Life Support Requirements, Minor.
        /// </summary>
        internal static string Trait_UnusualLifeSupportRequirementsMinor {
            get {
                return ResourceManager.GetString("Trait_UnusualLifeSupportRequirementsMinor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unusual Sleep Cycle.
        /// </summary>
        internal static string Trait_UnusualSleepCycle {
            get {
                return ResourceManager.GetString("Trait_UnusualSleepCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uplifited.
        /// </summary>
        internal static string Trait_Uplifited {
            get {
                return ResourceManager.GetString("Trait_Uplifited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Well-Travelled.
        /// </summary>
        internal static string Trait_WellTravelled {
            get {
                return ResourceManager.GetString("Trait_WellTravelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xeno-Empathy.
        /// </summary>
        internal static string Trait_XenoEmpathy {
            get {
                return ResourceManager.GetString("Trait_XenoEmpathy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acute Vision.
        /// </summary>
        internal static string Vision_AcuteVision {
            get {
                return ResourceManager.GetString("Vision_AcuteVision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blind.
        /// </summary>
        internal static string Vision_Blind {
            get {
                return ResourceManager.GetString("Vision_Blind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blindsight.
        /// </summary>
        internal static string Vision_Blindsight {
            get {
                return ResourceManager.GetString("Vision_Blindsight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colour Blindness.
        /// </summary>
        internal static string Vision_ColourBlindness {
            get {
                return ResourceManager.GetString("Vision_ColourBlindness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Darkvision.
        /// </summary>
        internal static string Vision_Darkvision {
            get {
                return ResourceManager.GetString("Vision_Darkvision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Blindness.
        /// </summary>
        internal static string Vision_LightBlindness {
            get {
                return ResourceManager.GetString("Vision_LightBlindness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Sensitivity.
        /// </summary>
        internal static string Vision_LightSensitivity {
            get {
                return ResourceManager.GetString("Vision_LightSensitivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low-light Vision.
        /// </summary>
        internal static string Vision_LowLightVision {
            get {
                return ResourceManager.GetString("Vision_LowLightVision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poor Vision.
        /// </summary>
        internal static string Vision_PoorVision {
            get {
                return ResourceManager.GetString("Vision_PoorVision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claws.
        /// </summary>
        internal static string Weapon_Claws {
            get {
                return ResourceManager.GetString("Weapon_Claws", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hooves.
        /// </summary>
        internal static string Weapon_Hooves {
            get {
                return ResourceManager.GetString("Weapon_Hooves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horns.
        /// </summary>
        internal static string Weapon_Horns {
            get {
                return ResourceManager.GetString("Weapon_Horns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stinger.
        /// </summary>
        internal static string Weapon_Stinger {
            get {
                return ResourceManager.GetString("Weapon_Stinger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teeth.
        /// </summary>
        internal static string Weapon_Teeth {
            get {
                return ResourceManager.GetString("Weapon_Teeth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thrasher.
        /// </summary>
        internal static string Weapon_Thrasher {
            get {
                return ResourceManager.GetString("Weapon_Thrasher", resourceCulture);
            }
        }
    }
}
