//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace org.DownesWard.Traveller.CharacterGeneration.Classic.SwordWorlds {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("org.DownesWard.Traveller.CharacterGeneration.Classic.SwordWorlds.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patrol.
        /// </summary>
        internal static string Career_Patrol {
            get {
                return ResourceManager.GetString("Career_Patrol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapiten.
        /// </summary>
        internal static string Rank_Kapiten {
            get {
                return ResourceManager.GetString("Rank_Kapiten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konstabel.
        /// </summary>
        internal static string Rank_Konstabel {
            get {
                return ResourceManager.GetString("Rank_Konstabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leutnant.
        /// </summary>
        internal static string Rank_Leutnant {
            get {
                return ResourceManager.GetString("Rank_Leutnant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oberst.
        /// </summary>
        internal static string Rank_Oberst {
            get {
                return ResourceManager.GetString("Rank_Oberst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overhode.
        /// </summary>
        internal static string Rank_Overhode {
            get {
                return ResourceManager.GetString("Rank_Overhode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overleutnant.
        /// </summary>
        internal static string Rank_Overleutnant {
            get {
                return ResourceManager.GetString("Rank_Overleutnant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patrolman.
        /// </summary>
        internal static string Rank_Patrolman {
            get {
                return ResourceManager.GetString("Rank_Patrolman", resourceCulture);
            }
        }
    }
}
