//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace org.DownesWard.Traveller.CharacterGeneration.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("org.DownesWard.Traveller.CharacterGeneration.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash.
        /// </summary>
        internal static string Benefit_Cash {
            get {
                return ResourceManager.GetString("Benefit_Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material.
        /// </summary>
        internal static string Benefit_Material {
            get {
                return ResourceManager.GetString("Benefit_Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string Button_No {
            get {
                return ResourceManager.GetString("Button_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Button_OK {
            get {
                return ResourceManager.GetString("Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Button_Yes {
            get {
                return ResourceManager.GetString("Button_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Died at age {0}.
        /// </summary>
        internal static string Jrn_Died {
            get {
                return ResourceManager.GetString("Jrn_Died", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drafted into {0}.
        /// </summary>
        internal static string Jrn_Drafted {
            get {
                return ResourceManager.GetString("Jrn_Drafted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Killed at age {0}.
        /// </summary>
        internal static string Jrn_Killed {
            get {
                return ResourceManager.GetString("Jrn_Killed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute {0} raised by {1}..
        /// </summary>
        internal static string Msg_Attribute_Raised {
            get {
                return ResourceManager.GetString("Msg_Attribute_Raised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your character died of old age at {0}..
        /// </summary>
        internal static string Msg_Died {
            get {
                return ResourceManager.GetString("Msg_Died", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You where drafted into the {0}..
        /// </summary>
        internal static string Msg_Drafted {
            get {
                return ResourceManager.GetString("Msg_Drafted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your character was killed at age {0}..
        /// </summary>
        internal static string Msg_Killed {
            get {
                return ResourceManager.GetString("Msg_Killed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received Psionic Training.
        /// </summary>
        internal static string Msg_Psionic_Training {
            get {
                return ResourceManager.GetString("Msg_Psionic_Training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received skill {0} level {1}..
        /// </summary>
        internal static string Msg_Skill_Received {
            get {
                return ResourceManager.GetString("Msg_Skill_Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your skill total exeeds the sum of INT and EDU, you need to reduce them..
        /// </summary>
        internal static string Msg_Skill_Total {
            get {
                return ResourceManager.GetString("Msg_Skill_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to persue another career?.
        /// </summary>
        internal static string Prompt_Another_Career {
            get {
                return ResourceManager.GetString("Prompt_Another_Career", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have {0} benefits rolls, no more than {1} can be on the cash table.
        /// </summary>
        internal static string Prompt_Benefit_Rolls {
            get {
                return ResourceManager.GetString("Prompt_Benefit_Rolls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please supply a character name..
        /// </summary>
        internal static string Prompt_CharacterName {
            get {
                return ResourceManager.GetString("Prompt_CharacterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You could not enlist. Submit to the draft?.
        /// </summary>
        internal static string Prompt_Draft {
            get {
                return ResourceManager.GetString("Prompt_Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File already exists. Overwrite?.
        /// </summary>
        internal static string Prompt_FileExists {
            get {
                return ResourceManager.GetString("Prompt_FileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to attend the psionic games?.
        /// </summary>
        internal static string Prompt_PsionicGames {
            get {
                return ResourceManager.GetString("Prompt_PsionicGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are now {0}. Do you want to re-enlist?.
        /// </summary>
        internal static string Prompt_Renlist {
            get {
                return ResourceManager.GetString("Prompt_Renlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a benefit table.
        /// </summary>
        internal static string Prompt_Select_Benefit_Table {
            get {
                return ResourceManager.GetString("Prompt_Select_Benefit_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a career.
        /// </summary>
        internal static string Prompt_Select_Career {
            get {
                return ResourceManager.GetString("Prompt_Select_Career", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a psionic talent.
        /// </summary>
        internal static string Prompt_Select_Psionic {
            get {
                return ResourceManager.GetString("Prompt_Select_Psionic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a skill.
        /// </summary>
        internal static string Prompt_Select_Skill {
            get {
                return ResourceManager.GetString("Prompt_Select_Skill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a skill table.
        /// </summary>
        internal static string Prompt_Select_Skill_Table {
            get {
                return ResourceManager.GetString("Prompt_Select_Skill_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a weapon.
        /// </summary>
        internal static string Prompt_Select_Weapon {
            get {
                return ResourceManager.GetString("Prompt_Select_Weapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a character.
        /// </summary>
        internal static string Prompt_SelectCharacter {
            get {
                return ResourceManager.GetString("Prompt_SelectCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a language.
        /// </summary>
        internal static string Prompt_SelectLanguage {
            get {
                return ResourceManager.GetString("Prompt_SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have received a weapon benefit, do you wish to take it as a skill instead?.
        /// </summary>
        internal static string Prompt_Weapon_Skill {
            get {
                return ResourceManager.GetString("Prompt_Weapon_Skill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traveller Career Generation.
        /// </summary>
        internal static string Title_App {
            get {
                return ResourceManager.GetString("Title_App", resourceCulture);
            }
        }
    }
}
