//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace org.DownesWard.Traveller.CharacterGeneration.Classic.Imperial.Citizen {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("org.DownesWard.Traveller.CharacterGeneration.Classic.Imperial.Citizen.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barbarian.
        /// </summary>
        internal static string Career_Barbarian {
            get {
                return ResourceManager.GetString("Career_Barbarian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belter.
        /// </summary>
        internal static string Career_Belter {
            get {
                return ResourceManager.GetString("Career_Belter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bureaucrat.
        /// </summary>
        internal static string Career_Bureaucrat {
            get {
                return ResourceManager.GetString("Career_Bureaucrat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diplomat.
        /// </summary>
        internal static string Career_Diplomat {
            get {
                return ResourceManager.GetString("Career_Diplomat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor.
        /// </summary>
        internal static string Career_Doctor {
            get {
                return ResourceManager.GetString("Career_Doctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flyer.
        /// </summary>
        internal static string Career_Flyer {
            get {
                return ResourceManager.GetString("Career_Flyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hunter.
        /// </summary>
        internal static string Career_Hunter {
            get {
                return ResourceManager.GetString("Career_Hunter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noble.
        /// </summary>
        internal static string Career_Noble {
            get {
                return ResourceManager.GetString("Career_Noble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pirate.
        /// </summary>
        internal static string Career_Pirate {
            get {
                return ResourceManager.GetString("Career_Pirate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rogue.
        /// </summary>
        internal static string Career_Rogue {
            get {
                return ResourceManager.GetString("Career_Rogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sailor.
        /// </summary>
        internal static string Career_Sailor {
            get {
                return ResourceManager.GetString("Career_Sailor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scientist.
        /// </summary>
        internal static string Career_Scientist {
            get {
                return ResourceManager.GetString("Career_Scientist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enlisted in {0} at age {1}.
        /// </summary>
        internal static string Msg_Enslisted {
            get {
                return ResourceManager.GetString("Msg_Enslisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enlistment in {0} refused at age {1}.
        /// </summary>
        internal static string Msg_Refused {
            get {
                return ResourceManager.GetString("Msg_Refused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commissioned as {0}.
        /// </summary>
        internal static string Prompt_Commissioned {
            get {
                return ResourceManager.GetString("Prompt_Commissioned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promoted to {0}.
        /// </summary>
        internal static string Prompt_Promoted {
            get {
                return ResourceManager.GetString("Prompt_Promoted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1st Secretary.
        /// </summary>
        internal static string Rank_1stSecretary {
            get {
                return ResourceManager.GetString("Rank_1stSecretary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2nd Secretary.
        /// </summary>
        internal static string Rank_2ndSecretary {
            get {
                return ResourceManager.GetString("Rank_2ndSecretary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3rd Secretary.
        /// </summary>
        internal static string Rank_3rdSecretary {
            get {
                return ResourceManager.GetString("Rank_3rdSecretary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admiral.
        /// </summary>
        internal static string Rank_Admiral {
            get {
                return ResourceManager.GetString("Rank_Admiral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air Marshall.
        /// </summary>
        internal static string Rank_AirMarshall {
            get {
                return ResourceManager.GetString("Rank_AirMarshall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambassador.
        /// </summary>
        internal static string Rank_Ambassador {
            get {
                return ResourceManager.GetString("Rank_Ambassador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistant Manager.
        /// </summary>
        internal static string Rank_AssistantManager {
            get {
                return ResourceManager.GetString("Rank_AssistantManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baron.
        /// </summary>
        internal static string Rank_Baron {
            get {
                return ResourceManager.GetString("Rank_Baron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belter.
        /// </summary>
        internal static string Rank_Belter {
            get {
                return ResourceManager.GetString("Rank_Belter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain.
        /// </summary>
        internal static string Rank_Captain {
            get {
                return ResourceManager.GetString("Rank_Captain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chief.
        /// </summary>
        internal static string Rank_Chief {
            get {
                return ResourceManager.GetString("Rank_Chief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clerk.
        /// </summary>
        internal static string Rank_Clerk {
            get {
                return ResourceManager.GetString("Rank_Clerk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commander.
        /// </summary>
        internal static string Rank_Commander {
            get {
                return ResourceManager.GetString("Rank_Commander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporal.
        /// </summary>
        internal static string Rank_Corporal {
            get {
                return ResourceManager.GetString("Rank_Corporal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counselor.
        /// </summary>
        internal static string Rank_Counselor {
            get {
                return ResourceManager.GetString("Rank_Counselor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        internal static string Rank_Count {
            get {
                return ResourceManager.GetString("Rank_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Director.
        /// </summary>
        internal static string Rank_Director {
            get {
                return ResourceManager.GetString("Rank_Director", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor.
        /// </summary>
        internal static string Rank_Doctor {
            get {
                return ResourceManager.GetString("Rank_Doctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duke.
        /// </summary>
        internal static string Rank_Duke {
            get {
                return ResourceManager.GetString("Rank_Duke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensign.
        /// </summary>
        internal static string Rank_Ensign {
            get {
                return ResourceManager.GetString("Rank_Ensign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executive.
        /// </summary>
        internal static string Rank_Executive {
            get {
                return ResourceManager.GetString("Rank_Executive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight Leader.
        /// </summary>
        internal static string Rank_FlightLeader {
            get {
                return ResourceManager.GetString("Rank_FlightLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flyer.
        /// </summary>
        internal static string Rank_Flyer {
            get {
                return ResourceManager.GetString("Rank_Flyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Leader.
        /// </summary>
        internal static string Rank_GroupLeader {
            get {
                return ResourceManager.GetString("Rank_GroupLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Henchman.
        /// </summary>
        internal static string Rank_Henchman {
            get {
                return ResourceManager.GetString("Rank_Henchman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hunter.
        /// </summary>
        internal static string Rank_Hunter {
            get {
                return ResourceManager.GetString("Rank_Hunter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knight.
        /// </summary>
        internal static string Rank_Knight {
            get {
                return ResourceManager.GetString("Rank_Knight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leader.
        /// </summary>
        internal static string Rank_Leader {
            get {
                return ResourceManager.GetString("Rank_Leader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lieutenant.
        /// </summary>
        internal static string Rank_Lieutenant {
            get {
                return ResourceManager.GetString("Rank_Lieutenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lt. Commander.
        /// </summary>
        internal static string Rank_LtCommander {
            get {
                return ResourceManager.GetString("Rank_LtCommander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        internal static string Rank_Manager {
            get {
                return ResourceManager.GetString("Rank_Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marquis.
        /// </summary>
        internal static string Rank_Marquis {
            get {
                return ResourceManager.GetString("Rank_Marquis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minister.
        /// </summary>
        internal static string Rank_Minister {
            get {
                return ResourceManager.GetString("Rank_Minister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noble.
        /// </summary>
        internal static string Rank_Noble {
            get {
                return ResourceManager.GetString("Rank_Noble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pilot.
        /// </summary>
        internal static string Rank_Pilot {
            get {
                return ResourceManager.GetString("Rank_Pilot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pirate.
        /// </summary>
        internal static string Rank_Pirate {
            get {
                return ResourceManager.GetString("Rank_Pirate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rogue.
        /// </summary>
        internal static string Rank_Rogue {
            get {
                return ResourceManager.GetString("Rank_Rogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sailor.
        /// </summary>
        internal static string Rank_Sailor {
            get {
                return ResourceManager.GetString("Rank_Sailor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scientist.
        /// </summary>
        internal static string Rank_Scientist {
            get {
                return ResourceManager.GetString("Rank_Scientist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sergeant.
        /// </summary>
        internal static string Rank_Sergeant {
            get {
                return ResourceManager.GetString("Rank_Sergeant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Squadron Leader.
        /// </summary>
        internal static string Rank_SquadronLeader {
            get {
                return ResourceManager.GetString("Rank_SquadronLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Major.
        /// </summary>
        internal static string Rank_StaffMajor {
            get {
                return ResourceManager.GetString("Rank_StaffMajor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor.
        /// </summary>
        internal static string Rank_Supervisor {
            get {
                return ResourceManager.GetString("Rank_Supervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warrior.
        /// </summary>
        internal static string Rank_Warrior {
            get {
                return ResourceManager.GetString("Rank_Warrior", resourceCulture);
            }
        }
    }
}
