//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace org.DownesWard.Traveller.CharacterGeneration.Cepheus.Commonwealth {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("org.DownesWard.Traveller.CharacterGeneration.Cepheus.Commonwealth.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenced Witch.
        /// </summary>
        internal static string Career_LicencedWitch {
            get {
                return ResourceManager.GetString("Career_LicencedWitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Military Witch.
        /// </summary>
        internal static string Career_MilitaryWitch {
            get {
                return ResourceManager.GetString("Career_MilitaryWitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rogue Witch.
        /// </summary>
        internal static string Career_RogueWitch {
            get {
                return ResourceManager.GetString("Career_RogueWitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Able Seaman.
        /// </summary>
        internal static string Rank_AbleSeaman {
            get {
                return ResourceManager.GetString("Rank_AbleSeaman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Able Starman.
        /// </summary>
        internal static string Rank_AbleStarman {
            get {
                return ResourceManager.GetString("Rank_AbleStarman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aircraftman.
        /// </summary>
        internal static string Rank_Aircraftman {
            get {
                return ResourceManager.GetString("Rank_Aircraftman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airman.
        /// </summary>
        internal static string Rank_Airman {
            get {
                return ResourceManager.GetString("Rank_Airman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airman First Class.
        /// </summary>
        internal static string Rank_AirmanFirstClass {
            get {
                return ResourceManager.GetString("Rank_AirmanFirstClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Leader.
        /// </summary>
        internal static string Rank_AreaLeader {
            get {
                return ResourceManager.GetString("Rank_AreaLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistant Coven Leader.
        /// </summary>
        internal static string Rank_AssistantCovenLeader {
            get {
                return ResourceManager.GetString("Rank_AssistantCovenLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chief Petty Officer.
        /// </summary>
        internal static string Rank_ChiefPettyOfficer {
            get {
                return ResourceManager.GetString("Rank_ChiefPettyOfficer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Sergeant Major.
        /// </summary>
        internal static string Rank_CompanySergeantMajor {
            get {
                return ResourceManager.GetString("Rank_CompanySergeantMajor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporal.
        /// </summary>
        internal static string Rank_Corporal {
            get {
                return ResourceManager.GetString("Rank_Corporal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coven Leader.
        /// </summary>
        internal static string Rank_CovenLeader {
            get {
                return ResourceManager.GetString("Rank_CovenLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight Sergeant.
        /// </summary>
        internal static string Rank_FlightSergeant {
            get {
                return ResourceManager.GetString("Rank_FlightSergeant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gunnery Sergeant.
        /// </summary>
        internal static string Rank_GunnerySergeant {
            get {
                return ResourceManager.GetString("Rank_GunnerySergeant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lance Corporal.
        /// </summary>
        internal static string Rank_LanceCorporal {
            get {
                return ResourceManager.GetString("Rank_LanceCorporal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leading Seaman.
        /// </summary>
        internal static string Rank_LeadingSeaman {
            get {
                return ResourceManager.GetString("Rank_LeadingSeaman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leading Starman.
        /// </summary>
        internal static string Rank_LeadingStarman {
            get {
                return ResourceManager.GetString("Rank_LeadingStarman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marine.
        /// </summary>
        internal static string Rank_Marine {
            get {
                return ResourceManager.GetString("Rank_Marine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Sergeant.
        /// </summary>
        internal static string Rank_MasterSergeant {
            get {
                return ResourceManager.GetString("Rank_MasterSergeant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petty Officer.
        /// </summary>
        internal static string Rank_PettyOfficer {
            get {
                return ResourceManager.GetString("Rank_PettyOfficer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        internal static string Rank_Private {
            get {
                return ResourceManager.GetString("Rank_Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regimental Sergeant Major.
        /// </summary>
        internal static string Rank_RegimentalSergeantMajor {
            get {
                return ResourceManager.GetString("Rank_RegimentalSergeantMajor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seaman.
        /// </summary>
        internal static string Rank_Seaman {
            get {
                return ResourceManager.GetString("Rank_Seaman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector Leader.
        /// </summary>
        internal static string Rank_SectorLeader {
            get {
                return ResourceManager.GetString("Rank_SectorLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senior Aircraftman.
        /// </summary>
        internal static string Rank_SeniorAircraftman {
            get {
                return ResourceManager.GetString("Rank_SeniorAircraftman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senior Airman.
        /// </summary>
        internal static string Rank_SeniorAirman {
            get {
                return ResourceManager.GetString("Rank_SeniorAirman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senior Witch.
        /// </summary>
        internal static string Rank_SeniorWitch {
            get {
                return ResourceManager.GetString("Rank_SeniorWitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sergeant.
        /// </summary>
        internal static string Rank_Sergeant {
            get {
                return ResourceManager.GetString("Rank_Sergeant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Sergeant.
        /// </summary>
        internal static string Rank_StaffSergeant {
            get {
                return ResourceManager.GetString("Rank_StaffSergeant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starman.
        /// </summary>
        internal static string Rank_Starman {
            get {
                return ResourceManager.GetString("Rank_Starman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Sergeant.
        /// </summary>
        internal static string Rank_TechnicalSergeant {
            get {
                return ResourceManager.GetString("Rank_TechnicalSergeant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainee Witch.
        /// </summary>
        internal static string Rank_TraineeWitch {
            get {
                return ResourceManager.GetString("Rank_TraineeWitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warrant Officer.
        /// </summary>
        internal static string Rank_WarrantOfficer {
            get {
                return ResourceManager.GetString("Rank_WarrantOfficer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witch.
        /// </summary>
        internal static string Rank_Witch {
            get {
                return ResourceManager.GetString("Rank_Witch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leader.
        /// </summary>
        internal static string Sex_Leader {
            get {
                return ResourceManager.GetString("Sex_Leader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technician.
        /// </summary>
        internal static string Sex_Technician {
            get {
                return ResourceManager.GetString("Sex_Technician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warrior.
        /// </summary>
        internal static string Sex_Warrior {
            get {
                return ResourceManager.GetString("Sex_Warrior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aircraft.
        /// </summary>
        internal static string Skill_Aircraft {
            get {
                return ResourceManager.GetString("Skill_Aircraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotor Aircraft.
        /// </summary>
        internal static string Skill_RotorAircraft {
            get {
                return ResourceManager.GetString("Skill_RotorAircraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle.
        /// </summary>
        internal static string Skill_Vehicle {
            get {
                return ResourceManager.GetString("Skill_Vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winged Aircraft.
        /// </summary>
        internal static string Skill_WingedAircraft {
            get {
                return ResourceManager.GetString("Skill_WingedAircraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Froog.
        /// </summary>
        internal static string Species_Froog {
            get {
                return ResourceManager.GetString("Species_Froog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K&apos;Hiff.
        /// </summary>
        internal static string Species_Khiff {
            get {
                return ResourceManager.GetString("Species_Khiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shanthaa.
        /// </summary>
        internal static string Species_Shanthaa {
            get {
                return ResourceManager.GetString("Species_Shanthaa", resourceCulture);
            }
        }
    }
}
