//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace org.DownesWard.Traveller.CharacterGeneration.Classic.Zhodani {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("org.DownesWard.Traveller.CharacterGeneration.Classic.Zhodani.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Army.
        /// </summary>
        internal static string Career_Army {
            get {
                return ResourceManager.GetString("Career_Army", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consular Guard.
        /// </summary>
        internal static string Career_ConsularGuard {
            get {
                return ResourceManager.GetString("Career_ConsularGuard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Government.
        /// </summary>
        internal static string Career_Government {
            get {
                return ResourceManager.GetString("Career_Government", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant.
        /// </summary>
        internal static string Career_Merchant {
            get {
                return ResourceManager.GetString("Career_Merchant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navy.
        /// </summary>
        internal static string Career_Navy {
            get {
                return ResourceManager.GetString("Career_Navy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prole.
        /// </summary>
        internal static string Career_Prole {
            get {
                return ResourceManager.GetString("Career_Prole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commissioned as {0}.
        /// </summary>
        internal static string Msg_Commissioned {
            get {
                return ResourceManager.GetString("Msg_Commissioned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enobled due to winning the Psionic games..
        /// </summary>
        internal static string Msg_Enobled {
            get {
                return ResourceManager.GetString("Msg_Enobled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promoted to {0}.
        /// </summary>
        internal static string Msg_Promoted {
            get {
                return ResourceManager.GetString("Msg_Promoted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSI Raised by one due to success in Psionic games..
        /// </summary>
        internal static string Msg_PsiRaised {
            get {
                return ResourceManager.GetString("Msg_PsiRaised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSI Raised by two due to winning the Psionic games.
        /// </summary>
        internal static string Msg_PsiRaised2 {
            get {
                return ResourceManager.GetString("Msg_PsiRaised2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSI reduced by 1 at end of term as not trained..
        /// </summary>
        internal static string Msg_PsiReduced {
            get {
                return ResourceManager.GetString("Msg_PsiReduced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1st Officer.
        /// </summary>
        internal static string Rank_1stOfficer {
            get {
                return ResourceManager.GetString("Rank_1stOfficer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2nd Officer.
        /// </summary>
        internal static string Rank_2ndOfficer {
            get {
                return ResourceManager.GetString("Rank_2ndOfficer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3rd Officer.
        /// </summary>
        internal static string Rank_3rdOfficer {
            get {
                return ResourceManager.GetString("Rank_3rdOfficer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4th Officer.
        /// </summary>
        internal static string Rank_4thOfficer {
            get {
                return ResourceManager.GetString("Rank_4thOfficer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admiral.
        /// </summary>
        internal static string Rank_Admiral {
            get {
                return ResourceManager.GetString("Rank_Admiral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistant Supervisor.
        /// </summary>
        internal static string Rank_AssistantSupervisor {
            get {
                return ResourceManager.GetString("Rank_AssistantSupervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain.
        /// </summary>
        internal static string Rank_Captain {
            get {
                return ResourceManager.GetString("Rank_Captain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clerk.
        /// </summary>
        internal static string Rank_Clerk {
            get {
                return ResourceManager.GetString("Rank_Clerk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colonel.
        /// </summary>
        internal static string Rank_Colonel {
            get {
                return ResourceManager.GetString("Rank_Colonel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commander.
        /// </summary>
        internal static string Rank_Commander {
            get {
                return ResourceManager.GetString("Rank_Commander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consul.
        /// </summary>
        internal static string Rank_Consul {
            get {
                return ResourceManager.GetString("Rank_Consul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deck Hand.
        /// </summary>
        internal static string Rank_DeckHand {
            get {
                return ResourceManager.GetString("Rank_DeckHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Director.
        /// </summary>
        internal static string Rank_Director {
            get {
                return ResourceManager.GetString("Rank_Director", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensign.
        /// </summary>
        internal static string Rank_Ensign {
            get {
                return ResourceManager.GetString("Rank_Ensign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executive.
        /// </summary>
        internal static string Rank_Executive {
            get {
                return ResourceManager.GetString("Rank_Executive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string Rank_General {
            get {
                return ResourceManager.GetString("Rank_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Consul.
        /// </summary>
        internal static string Rank_HighConsul {
            get {
                return ResourceManager.GetString("Rank_HighConsul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lieutenant.
        /// </summary>
        internal static string Rank_Lieutenant {
            get {
                return ResourceManager.GetString("Rank_Lieutenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lt. Colonel.
        /// </summary>
        internal static string Rank_LtColonel {
            get {
                return ResourceManager.GetString("Rank_LtColonel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lt. Commander.
        /// </summary>
        internal static string Rank_LtCommander {
            get {
                return ResourceManager.GetString("Rank_LtCommander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major.
        /// </summary>
        internal static string Rank_Major {
            get {
                return ResourceManager.GetString("Rank_Major", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        internal static string Rank_Manager {
            get {
                return ResourceManager.GetString("Rank_Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Midshipman.
        /// </summary>
        internal static string Rank_Midshipman {
            get {
                return ResourceManager.GetString("Rank_Midshipman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senior Captain.
        /// </summary>
        internal static string Rank_SeniorCaptain {
            get {
                return ResourceManager.GetString("Rank_SeniorCaptain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senior Executive.
        /// </summary>
        internal static string Rank_SeniorExecutive {
            get {
                return ResourceManager.GetString("Rank_SeniorExecutive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spacer.
        /// </summary>
        internal static string Rank_Spacer {
            get {
                return ResourceManager.GetString("Rank_Spacer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subaltern.
        /// </summary>
        internal static string Rank_Subaltern {
            get {
                return ResourceManager.GetString("Rank_Subaltern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor.
        /// </summary>
        internal static string Rank_Supervisor {
            get {
                return ResourceManager.GetString("Rank_Supervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trooper.
        /// </summary>
        internal static string Rank_Trooper {
            get {
                return ResourceManager.GetString("Rank_Trooper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker.
        /// </summary>
        internal static string Rank_Worker {
            get {
                return ResourceManager.GetString("Rank_Worker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Consul.
        /// </summary>
        internal static string Rank_WorldConsul {
            get {
                return ResourceManager.GetString("Rank_WorldConsul", resourceCulture);
            }
        }
    }
}
