//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace org.DownesWard.Traveller.CharacterGeneration.Classic.Darrian {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("org.DownesWard.Traveller.CharacterGeneration.Classic.Darrian.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic.
        /// </summary>
        internal static string Career_Academic {
            get {
                return ResourceManager.GetString("Career_Academic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Army.
        /// </summary>
        internal static string Career_Army {
            get {
                return ResourceManager.GetString("Career_Army", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchants.
        /// </summary>
        internal static string Career_Merchants {
            get {
                return ResourceManager.GetString("Career_Merchants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navy.
        /// </summary>
        internal static string Career_Navy {
            get {
                return ResourceManager.GetString("Career_Navy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noble.
        /// </summary>
        internal static string Career_Noble {
            get {
                return ResourceManager.GetString("Career_Noble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Arm.
        /// </summary>
        internal static string Career_SpecialArm {
            get {
                return ResourceManager.GetString("Career_SpecialArm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic.
        /// </summary>
        internal static string Rank_Academic {
            get {
                return ResourceManager.GetString("Rank_Academic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asst. Instructor.
        /// </summary>
        internal static string Rank_AsstInstructor {
            get {
                return ResourceManager.GetString("Rank_AsstInstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asst. Professor.
        /// </summary>
        internal static string Rank_AsstProfessor {
            get {
                return ResourceManager.GetString("Rank_AsstProfessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dean.
        /// </summary>
        internal static string Rank_Dean {
            get {
                return ResourceManager.GetString("Rank_Dean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructor.
        /// </summary>
        internal static string Rank_Instructor {
            get {
                return ResourceManager.GetString("Rank_Instructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professor.
        /// </summary>
        internal static string Rank_Professor {
            get {
                return ResourceManager.GetString("Rank_Professor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher.
        /// </summary>
        internal static string Rank_Teacher {
            get {
                return ResourceManager.GetString("Rank_Teacher", resourceCulture);
            }
        }
    }
}
