//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace org.DownesWard.Traveller.CharacterGeneration.Classic.Darrian {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("org.DownesWard.Traveller.CharacterGeneration.Classic.Darrian.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic.
        /// </summary>
        internal static string Career_Academic {
            get {
                return ResourceManager.GetString("Career_Academic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Army.
        /// </summary>
        internal static string Career_Army {
            get {
                return ResourceManager.GetString("Career_Army", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchants.
        /// </summary>
        internal static string Career_Merchants {
            get {
                return ResourceManager.GetString("Career_Merchants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navy.
        /// </summary>
        internal static string Career_Navy {
            get {
                return ResourceManager.GetString("Career_Navy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noble.
        /// </summary>
        internal static string Career_Noble {
            get {
                return ResourceManager.GetString("Career_Noble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Arm.
        /// </summary>
        internal static string Career_SpecialArm {
            get {
                return ResourceManager.GetString("Career_SpecialArm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1st Officer.
        /// </summary>
        internal static string Rank_1stOfficer {
            get {
                return ResourceManager.GetString("Rank_1stOfficer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2nd Officer.
        /// </summary>
        internal static string Rank_2ndOfficer {
            get {
                return ResourceManager.GetString("Rank_2ndOfficer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3rd Officer.
        /// </summary>
        internal static string Rank_3rdOfficer {
            get {
                return ResourceManager.GetString("Rank_3rdOfficer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4th Officer.
        /// </summary>
        internal static string Rank_4thOfficer {
            get {
                return ResourceManager.GetString("Rank_4thOfficer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic.
        /// </summary>
        internal static string Rank_Academic {
            get {
                return ResourceManager.GetString("Rank_Academic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admiral.
        /// </summary>
        internal static string Rank_Admiral {
            get {
                return ResourceManager.GetString("Rank_Admiral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asst. Instructor.
        /// </summary>
        internal static string Rank_AsstInstructor {
            get {
                return ResourceManager.GetString("Rank_AsstInstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asst. Professor.
        /// </summary>
        internal static string Rank_AsstProfessor {
            get {
                return ResourceManager.GetString("Rank_AsstProfessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baron.
        /// </summary>
        internal static string Rank_Baron {
            get {
                return ResourceManager.GetString("Rank_Baron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain.
        /// </summary>
        internal static string Rank_Captain {
            get {
                return ResourceManager.GetString("Rank_Captain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colonel.
        /// </summary>
        internal static string Rank_Colonel {
            get {
                return ResourceManager.GetString("Rank_Colonel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commander.
        /// </summary>
        internal static string Rank_Commander {
            get {
                return ResourceManager.GetString("Rank_Commander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        internal static string Rank_Count {
            get {
                return ResourceManager.GetString("Rank_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dean.
        /// </summary>
        internal static string Rank_Dean {
            get {
                return ResourceManager.GetString("Rank_Dean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duke.
        /// </summary>
        internal static string Rank_Duke {
            get {
                return ResourceManager.GetString("Rank_Duke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensign.
        /// </summary>
        internal static string Rank_Ensign {
            get {
                return ResourceManager.GetString("Rank_Ensign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string Rank_General {
            get {
                return ResourceManager.GetString("Rank_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructor.
        /// </summary>
        internal static string Rank_Instructor {
            get {
                return ResourceManager.GetString("Rank_Instructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knight.
        /// </summary>
        internal static string Rank_Knight {
            get {
                return ResourceManager.GetString("Rank_Knight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lieutenant.
        /// </summary>
        internal static string Rank_Lieutenant {
            get {
                return ResourceManager.GetString("Rank_Lieutenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lt. Colonel.
        /// </summary>
        internal static string Rank_LtColonel {
            get {
                return ResourceManager.GetString("Rank_LtColonel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lt. Commander.
        /// </summary>
        internal static string Rank_LtCommander {
            get {
                return ResourceManager.GetString("Rank_LtCommander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major.
        /// </summary>
        internal static string Rank_Major {
            get {
                return ResourceManager.GetString("Rank_Major", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marquis.
        /// </summary>
        internal static string Rank_Marquis {
            get {
                return ResourceManager.GetString("Rank_Marquis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noble.
        /// </summary>
        internal static string Rank_Noble {
            get {
                return ResourceManager.GetString("Rank_Noble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professor.
        /// </summary>
        internal static string Rank_Professor {
            get {
                return ResourceManager.GetString("Rank_Professor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space Hand.
        /// </summary>
        internal static string Rank_SpaceHand {
            get {
                return ResourceManager.GetString("Rank_SpaceHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spacer.
        /// </summary>
        internal static string Rank_Spacer {
            get {
                return ResourceManager.GetString("Rank_Spacer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sr Captain.
        /// </summary>
        internal static string Rank_SrCaptain {
            get {
                return ResourceManager.GetString("Rank_SrCaptain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher.
        /// </summary>
        internal static string Rank_Teacher {
            get {
                return ResourceManager.GetString("Rank_Teacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trooper.
        /// </summary>
        internal static string Rank_Trooper {
            get {
                return ResourceManager.GetString("Rank_Trooper", resourceCulture);
            }
        }
    }
}
